/* BROSIN · i18n — detección automática + selector de idioma (9 idiomas)
   Traduce SOLO la interfaz (los datos de locales no se tocan).
   La firma "Bro, no te quedes sin, Brosin." se mantiene en español (marca). */
(function(){
  var DICT = {
   es:{soon:"Muy pronto",mp_h1:"El mapa de la cultura cannábica está en camino",mp_lead:"Clubes, coffeeshops, grow shops y tiendas de CBD de España, Portugal y toda Europa. Le estamos dando los últimos toques.",mp_cta:"¿Tienes un local? Añádelo gratis →",mp_sub:"Club, grow shop o tienda de CBD: entra antes que nadie en el mapa. Es gratis.",legal_mini:"Guía informativa · aquí no se vende cannabis · solo mayores de 18 años · consume con responsabilidad",f_title:"Añade tu local a Brosin",f_intro:"Rellena los datos de tu club, grow shop o tienda de CBD. Es gratis salir en el mapa. Al enviar, nos llegan directamente y te contactamos.",f_note:"Lo imprescindible es nombre, tipo, ciudad y dirección. El resto mejora tu ficha pero puede ir vacío.",l_nombre:"Nombre del local",l_tipo:"Tipo",opt_elige:"Elige…",opt_csc:"Club Social de Cannabis (CSC)",opt_grow:"Grow shop",opt_cbd:"Tienda de CBD",opt_coffee:"Coffeeshop",opt_med:"Medicinal",opt_emp:"Empresa del sector",l_edad:"¿Acceso solo adultos?",opt_noind:"No indicar",l_ciudad:"Ciudad",l_prov:"Provincia",l_dir:"Dirección completa",l_tel:"Teléfono / WhatsApp",l_email:"Email de contacto",l_horario:"Horario",l_redes:"Instagram / Web",l_desc:"Descripción corta",ph_nombre:"Ej: Brosin CSC",ph_ciudad:"Ej: Torre del Mar",ph_prov:"Ej: Málaga",ph_dir:"Calle, número, CP, ciudad",ph_tel:"Ej: 600 000 000",ph_email:"tucorreo@ejemplo.com",ph_horario:"Ej: L–S 12:00–23:30",ph_redes:"Ej: @tuclub o tuweb.es",ph_desc:"Ambiente, qué ofreces…",consent:"Soy responsable de este local y autorizo que aparezca en Brosin con estos datos. Sé que puedo pedir la baja cuando quiera escribiendo a hola@brosin.app.",btn:"Enviar mi local a Brosin",sending:"Enviando…",err:"Ups, algo falló al enviar. Inténtalo de nuevo o escríbenos a hola@brosin.app.",legal_form:"Tus datos se tratan conforme al RGPD solo para gestionar tu alta en Brosin. Responsable: Brosin · hola@brosin.app. Solo +18.",ok_title:"¡Recibido, bro!",ok_msg:"Ya tenemos tu local. Le echamos un ojo y te contactamos para dejarlo perfecto en el mapa. ¡Gracias por sumarte a la colmena!"},
   en:{soon:"Coming soon",mp_h1:"The map of cannabis culture is on its way",mp_lead:"Clubs, coffeeshops, grow shops and CBD stores from Spain, Portugal and all of Europe. We're putting the finishing touches on it.",mp_cta:"Got a place? Add it for free →",mp_sub:"Club, grow shop or CBD store: get on the map before anyone else. It's free.",legal_mini:"Informational guide · no cannabis is sold here · 18+ only · consume responsibly",f_title:"Add your place to Brosin",f_intro:"Fill in the details of your club, grow shop or CBD store. Getting on the map is free. When you submit, it comes straight to us and we'll get in touch.",f_note:"The essentials are name, type, city and address. The rest improves your listing but can be left empty.",l_nombre:"Place name",l_tipo:"Type",opt_elige:"Choose…",opt_csc:"Cannabis Social Club (CSC)",opt_grow:"Grow shop",opt_cbd:"CBD store",opt_coffee:"Coffeeshop",opt_med:"Medical",opt_emp:"Industry business",l_edad:"Adults-only access?",opt_noind:"Don't specify",l_ciudad:"City",l_prov:"Province",l_dir:"Full address",l_tel:"Phone / WhatsApp",l_email:"Contact email",l_horario:"Opening hours",l_redes:"Instagram / Website",l_desc:"Short description",ph_nombre:"e.g. Brosin CSC",ph_ciudad:"e.g. Torre del Mar",ph_prov:"e.g. Málaga",ph_dir:"Street, number, postcode, city",ph_tel:"e.g. 600 000 000",ph_email:"youremail@example.com",ph_horario:"e.g. Mon–Sat 12:00–23:30",ph_redes:"e.g. @yourclub or yoursite.com",ph_desc:"Vibe, what you offer…",consent:"I'm responsible for this place and I authorise it to appear on Brosin with these details. I know I can ask to be removed anytime by writing to hola@brosin.app.",btn:"Send my place to Brosin",sending:"Sending…",err:"Oops, something went wrong while sending. Try again or write to us at hola@brosin.app.",legal_form:"Your data is processed under GDPR solely to manage your listing on Brosin. Controller: Brosin · hola@brosin.app. 18+ only.",ok_title:"Got it, bro!",ok_msg:"We've got your place. We'll take a look and get in touch to make it perfect on the map. Thanks for joining the hive!"},
   de:{soon:"Ganz bald",mp_h1:"Die Karte der Cannabis-Kultur ist unterwegs",mp_lead:"Clubs, Coffeeshops, Grow Shops und CBD-Läden aus Spanien, Portugal und ganz Europa. Wir geben gerade den letzten Schliff.",mp_cta:"Hast du ein Lokal? Trag es kostenlos ein →",mp_sub:"Club, Grow Shop oder CBD-Laden: sei vor allen anderen auf der Karte. Kostenlos.",legal_mini:"Informationsguide · hier wird kein Cannabis verkauft · nur ab 18 · konsumiere verantwortungsvoll",f_title:"Füge dein Lokal zu Brosin hinzu",f_intro:"Trag die Daten deines Clubs, Grow Shops oder CBD-Ladens ein. Auf die Karte zu kommen ist kostenlos. Sobald du absendest, erreicht uns alles direkt und wir melden uns.",f_note:"Unverzichtbar sind Name, Typ, Stadt und Adresse. Der Rest verbessert deinen Eintrag, kann aber leer bleiben.",l_nombre:"Name des Lokals",l_tipo:"Typ",opt_elige:"Wähle…",opt_csc:"Cannabis Social Club (CSC)",opt_grow:"Grow Shop",opt_cbd:"CBD-Laden",opt_coffee:"Coffeeshop",opt_med:"Medizinisch",opt_emp:"Unternehmen der Branche",l_edad:"Zugang nur für Erwachsene?",opt_noind:"Keine Angabe",l_ciudad:"Stadt",l_prov:"Region",l_dir:"Vollständige Adresse",l_tel:"Telefon / WhatsApp",l_email:"Kontakt-E-Mail",l_horario:"Öffnungszeiten",l_redes:"Instagram / Website",l_desc:"Kurzbeschreibung",ph_nombre:"z. B. Brosin CSC",ph_ciudad:"z. B. Torre del Mar",ph_prov:"z. B. Málaga",ph_dir:"Straße, Nummer, PLZ, Stadt",ph_tel:"z. B. 600 000 000",ph_email:"deinemail@beispiel.com",ph_horario:"z. B. Mo–Sa 12:00–23:30",ph_redes:"z. B. @deinclub oder deineseite.de",ph_desc:"Ambiente, was du bietest…",consent:"Ich bin für dieses Lokal verantwortlich und erlaube, dass es mit diesen Daten auf Brosin erscheint. Mir ist klar, dass ich die Löschung jederzeit per E-Mail an hola@brosin.app beantragen kann.",btn:"Mein Lokal an Brosin senden",sending:"Wird gesendet…",err:"Ups, beim Senden ist etwas schiefgelaufen. Versuch es noch mal oder schreib uns an hola@brosin.app.",legal_form:"Deine Daten werden gemäß RGPD ausschließlich zur Verwaltung deines Eintrags bei Brosin verarbeitet. Verantwortlicher: Brosin · hola@brosin.app. Nur ab 18.",ok_title:"Angekommen, Bro!",ok_msg:"Wir haben dein Lokal. Wir schauen es uns an und melden uns, um es perfekt auf der Karte zu platzieren. Danke, dass du zum Schwarm dazugehörst!"},
   fr:{soon:"Très bientôt",mp_h1:"La carte de la culture cannabique arrive",mp_lead:"Clubs, coffeeshops, grow shops et boutiques de CBD d'Espagne, du Portugal et de toute l'Europe. On y met la dernière touche.",mp_cta:"Tu as un local ? Ajoute-le gratuitement →",mp_sub:"Club, grow shop ou boutique de CBD : entre sur la carte avant tout le monde. C'est gratuit.",legal_mini:"Guide informatif · ici on ne vend pas de cannabis · réservé aux plus de 18 ans · consomme avec responsabilité",f_title:"Ajoute ton local à Brosin",f_intro:"Remplis les infos de ton club, grow shop ou boutique de CBD. Apparaître sur la carte est gratuit. En envoyant, tout nous arrive directement et on te contacte.",f_note:"L'essentiel, c'est le nom, le type, la ville et l'adresse. Le reste améliore ta fiche mais peut rester vide.",l_nombre:"Nom du local",l_tipo:"Type",opt_elige:"Choisis…",opt_csc:"Club Social de Cannabis (CSC)",opt_grow:"Grow shop",opt_cbd:"Boutique de CBD",opt_coffee:"Coffeeshop",opt_med:"Médicinal",opt_emp:"Entreprise du secteur",l_edad:"Accès réservé aux adultes ?",opt_noind:"Ne pas préciser",l_ciudad:"Ville",l_prov:"Région",l_dir:"Adresse complète",l_tel:"Téléphone / WhatsApp",l_email:"E-mail de contact",l_horario:"Horaires",l_redes:"Instagram / Site web",l_desc:"Description courte",ph_nombre:"Ex. : Brosin CSC",ph_ciudad:"Ex. : Torre del Mar",ph_prov:"Ex. : Málaga",ph_dir:"Rue, numéro, code postal, ville",ph_tel:"Ex. : 600 000 000",ph_email:"tonemail@exemple.com",ph_horario:"Ex. : lun–sam 12:00–23:30",ph_redes:"Ex. : @tonclub ou tonsite.fr",ph_desc:"Ambiance, ce que tu proposes…",consent:"Je suis responsable de ce local et j'autorise son affichage sur Brosin avec ces données. Je sais que je peux demander son retrait à tout moment en écrivant à hola@brosin.app.",btn:"Envoyer mon local à Brosin",sending:"Envoi…",err:"Oups, l'envoi a échoué. Réessaie ou écris-nous à hola@brosin.app.",legal_form:"Tes données sont traitées conformément au RGPD uniquement pour gérer ton inscription sur Brosin. Responsable : Brosin · hola@brosin.app. Réservé aux +18.",ok_title:"Bien reçu, bro !",ok_msg:"On a bien ton local. On y jette un œil et on te contacte pour le rendre parfait sur la carte. Merci de rejoindre la ruche !"},
   nl:{soon:"Heel binnenkort",mp_h1:"De kaart van de cannabiscultuur is onderweg",mp_lead:"Clubs, coffeeshops, growshops en CBD-winkels uit Spanje, Portugal en heel Europa. We leggen de laatste hand aan.",mp_cta:"Heb je een zaak? Voeg 'm gratis toe →",mp_sub:"Club, growshop of CBD-winkel: sta als eerste op de kaart. Het is gratis.",legal_mini:"Informatieve gids · hier wordt geen cannabis verkocht · alleen 18+ · gebruik verantwoord",f_title:"Voeg je zaak toe aan Brosin",f_intro:"Vul de gegevens van je club, growshop of CBD-winkel in. Op de kaart komen is gratis. Als je verstuurt, komt alles direct bij ons binnen en nemen we contact met je op.",f_note:"Onmisbaar zijn naam, type, stad en adres. De rest verbetert je vermelding, maar mag leeg blijven.",l_nombre:"Naam van de zaak",l_tipo:"Type",opt_elige:"Kies…",opt_csc:"Cannabis Social Club (CSC)",opt_grow:"Growshop",opt_cbd:"CBD-winkel",opt_coffee:"Coffeeshop",opt_med:"Medicinaal",opt_emp:"Bedrijf uit de sector",l_edad:"Alleen toegang voor volwassenen?",opt_noind:"Niet aangeven",l_ciudad:"Stad",l_prov:"Provincie",l_dir:"Volledig adres",l_tel:"Telefoon / WhatsApp",l_email:"Contact-e-mail",l_horario:"Openingstijden",l_redes:"Instagram / Website",l_desc:"Korte beschrijving",ph_nombre:"Bijv. Brosin CSC",ph_ciudad:"Bijv. Torre del Mar",ph_prov:"Bijv. Málaga",ph_dir:"Straat, nummer, postcode, stad",ph_tel:"Bijv. 600 000 000",ph_email:"jouwmail@voorbeeld.com",ph_horario:"Bijv. ma–za 12:00–23:30",ph_redes:"Bijv. @jouwclub of jouwsite.nl",ph_desc:"Sfeer, wat je aanbiedt…",consent:"Ik ben verantwoordelijk voor deze zaak en geef toestemming dat die met deze gegevens op Brosin verschijnt. Ik weet dat ik me altijd kan laten verwijderen door te mailen naar hola@brosin.app.",btn:"Mijn zaak naar Brosin sturen",sending:"Versturen…",err:"Oeps, er ging iets mis bij het versturen. Probeer het opnieuw of mail ons op hola@brosin.app.",legal_form:"Je gegevens worden conform de RGPD alleen verwerkt om je aanmelding bij Brosin te beheren. Verwerkingsverantwoordelijke: Brosin · hola@brosin.app. Alleen +18.",ok_title:"Ontvangen, bro!",ok_msg:"We hebben je zaak binnen. We kijken ernaar en nemen contact met je op om 'm perfect op de kaart te zetten. Bedankt dat je je bij de zwerm aansluit!"},
   it:{soon:"Molto presto",mp_h1:"La mappa della cultura cannabica è in arrivo",mp_lead:"Club, coffeeshop, grow shop e negozi di CBD di Spagna, Portogallo e tutta Europa. Stiamo dando gli ultimi ritocchi.",mp_cta:"Hai un locale? Aggiungilo gratis →",mp_sub:"Club, grow shop o negozio di CBD: entra sulla mappa prima di tutti. È gratis.",legal_mini:"Guida informativa · qui non si vende cannabis · solo maggiori di 18 anni · consuma con responsabilità",f_title:"Aggiungi il tuo locale a Brosin",f_intro:"Inserisci i dati del tuo club, grow shop o negozio di CBD. Comparire sulla mappa è gratis. Quando invii, ci arriva tutto direttamente e ti contattiamo.",f_note:"L'indispensabile è nome, tipo, città e indirizzo. Il resto migliora la tua scheda ma può restare vuoto.",l_nombre:"Nome del locale",l_tipo:"Tipo",opt_elige:"Scegli…",opt_csc:"Cannabis Social Club (CSC)",opt_grow:"Grow shop",opt_cbd:"Negozio di CBD",opt_coffee:"Coffeeshop",opt_med:"Medicinale",opt_emp:"Azienda del settore",l_edad:"Accesso solo per adulti?",opt_noind:"Non specificare",l_ciudad:"Città",l_prov:"Provincia",l_dir:"Indirizzo completo",l_tel:"Telefono / WhatsApp",l_email:"Email di contatto",l_horario:"Orari",l_redes:"Instagram / Sito web",l_desc:"Descrizione breve",ph_nombre:"Es. Brosin CSC",ph_ciudad:"Es. Torre del Mar",ph_prov:"Es. Málaga",ph_dir:"Via, numero, CAP, città",ph_tel:"Es. 600 000 000",ph_email:"latuamail@esempio.com",ph_horario:"Es. lun–sab 12:00–23:30",ph_redes:"Es. @tuoclub o tuosito.it",ph_desc:"Atmosfera, cosa offri…",consent:"Sono responsabile di questo locale e autorizzo la sua comparsa su Brosin con questi dati. So che posso chiedere la cancellazione quando voglio scrivendo a hola@brosin.app.",btn:"Invia il mio locale a Brosin",sending:"Invio in corso…",err:"Ops, qualcosa è andato storto durante l'invio. Riprova o scrivici a hola@brosin.app.",legal_form:"I tuoi dati sono trattati in conformità al RGPD solo per gestire la tua iscrizione su Brosin. Titolare: Brosin · hola@brosin.app. Solo +18.",ok_title:"Ricevuto, bro!",ok_msg:"Abbiamo il tuo locale. Gli diamo un'occhiata e ti contattiamo per renderlo perfetto sulla mappa. Grazie per esserti unito all'alveare!"},
   pt:{soon:"Muito em breve",mp_h1:"O mapa da cultura canábica está a caminho",mp_lead:"Clubes, coffeeshops, grow shops e lojas de CBD de Espanha, Portugal e toda a Europa. Estamos a dar os últimos retoques.",mp_cta:"Tens um espaço? Adiciona-o grátis →",mp_sub:"Clube, grow shop ou loja de CBD: entra no mapa antes de todos. É grátis.",legal_mini:"Guia informativo · aqui não se vende cannabis · apenas maiores de 18 anos · consome com responsabilidade",f_title:"Adiciona o teu espaço ao Brosin",f_intro:"Preenche os dados do teu clube, grow shop ou loja de CBD. Aparecer no mapa é grátis. Ao enviar, chega tudo diretamente a nós e entramos em contacto.",f_note:"O essencial é o nome, o tipo, a cidade e a morada. O resto melhora a tua ficha, mas pode ficar vazio.",l_nombre:"Nome do espaço",l_tipo:"Tipo",opt_elige:"Escolhe…",opt_csc:"Clube Social de Cannabis (CSC)",opt_grow:"Grow shop",opt_cbd:"Loja de CBD",opt_coffee:"Coffeeshop",opt_med:"Medicinal",opt_emp:"Empresa do setor",l_edad:"Acesso só para adultos?",opt_noind:"Não indicar",l_ciudad:"Cidade",l_prov:"Distrito",l_dir:"Morada completa",l_tel:"Telefone / WhatsApp",l_email:"Email de contacto",l_horario:"Horário",l_redes:"Instagram / Site",l_desc:"Descrição curta",ph_nombre:"Ex.: Brosin CSC",ph_ciudad:"Ex.: Torre del Mar",ph_prov:"Ex.: Málaga",ph_dir:"Rua, número, código postal, cidade",ph_tel:"Ex.: 600 000 000",ph_email:"oteuemail@exemplo.com",ph_horario:"Ex.: seg–sáb 12:00–23:30",ph_redes:"Ex.: @oteuclube ou oteusite.pt",ph_desc:"Ambiente, o que ofereces…",consent:"Sou responsável por este espaço e autorizo que apareça no Brosin com estes dados. Sei que posso pedir a remoção quando quiser, escrevendo para hola@brosin.app.",btn:"Enviar o meu espaço ao Brosin",sending:"A enviar…",err:"Ups, algo falhou no envio. Tenta de novo ou escreve-nos para hola@brosin.app.",legal_form:"Os teus dados são tratados de acordo com o RGPD apenas para gerir a tua inscrição no Brosin. Responsável: Brosin · hola@brosin.app. Apenas +18.",ok_title:"Recebido, bro!",ok_msg:"Já temos o teu espaço. Vamos dar uma olhadela e entramos em contacto para o deixar perfeito no mapa. Obrigado por te juntares à colmeia!"},
   sv:{soon:"Mycket snart",mp_h1:"Kartan över cannabiskulturen är på väg",mp_lead:"Klubbar, coffeeshops, grow shops och CBD-butiker i Spanien, Portugal och hela Europa. Vi lägger sista handen vid den.",mp_cta:"Har du ett ställe? Lägg till det gratis →",mp_sub:"Klubb, grow shop eller CBD-butik: kom med på kartan före alla andra. Det är gratis.",legal_mini:"Informationsguide · här säljs ingen cannabis · endast 18+ · konsumera ansvarsfullt",f_title:"Lägg till ditt ställe i Brosin",f_intro:"Fyll i uppgifterna för din klubb, grow shop eller CBD-butik. Att komma med på kartan är gratis. När du skickar in når det oss direkt och vi hör av oss.",f_note:"Det nödvändiga är namn, typ, stad och adress. Resten förbättrar din profil men kan lämnas tomt.",l_nombre:"Ställets namn",l_tipo:"Typ",opt_elige:"Välj…",opt_csc:"Cannabis Social Club (CSC)",opt_grow:"Grow shop",opt_cbd:"CBD-butik",opt_coffee:"Coffeeshop",opt_med:"Medicinsk",opt_emp:"Företag i branschen",l_edad:"Endast tillträde för vuxna?",opt_noind:"Vill inte ange",l_ciudad:"Stad",l_prov:"Region",l_dir:"Fullständig adress",l_tel:"Telefon / WhatsApp",l_email:"Kontakt-e-post",l_horario:"Öppettider",l_redes:"Instagram / Webbplats",l_desc:"Kort beskrivning",ph_nombre:"T.ex. Brosin CSC",ph_ciudad:"T.ex. Torre del Mar",ph_prov:"T.ex. Málaga",ph_dir:"Gata, nummer, postnummer, stad",ph_tel:"T.ex. 600 000 000",ph_email:"dinmejl@exempel.com",ph_horario:"T.ex. mån–lör 12:00–23:30",ph_redes:"T.ex. @dinklubb eller dinsajt.se",ph_desc:"Stämning, vad du erbjuder…",consent:"Jag ansvarar för det här stället och godkänner att det visas på Brosin med dessa uppgifter. Jag vet att jag när som helst kan begära att bli borttagen genom att mejla till hola@brosin.app.",btn:"Skicka mitt ställe till Brosin",sending:"Skickar…",err:"Hoppsan, något gick fel vid skickandet. Försök igen eller mejla oss på hola@brosin.app.",legal_form:"Dina uppgifter behandlas enligt RGPD enbart för att hantera din registrering på Brosin. Personuppgiftsansvarig: Brosin · hola@brosin.app. Endast +18.",ok_title:"Mottaget, bro!",ok_msg:"Vi har ditt ställe. Vi tittar på det och hör av oss för att göra det perfekt på kartan. Tack för att du går med i kupan!"},
   pl:{soon:"Już wkrótce",mp_h1:"Mapa kultury konopnej jest już w drodze",mp_lead:"Kluby, coffeeshopy, grow shopy i sklepy z CBD z Hiszpanii, Portugalii i całej Europy. Właśnie dopracowujemy szczegóły.",mp_cta:"Masz lokal? Dodaj go za darmo →",mp_sub:"Klub, grow shop albo sklep z CBD: pojaw się na mapie przed innymi. To za darmo.",legal_mini:"Przewodnik informacyjny · tu nie sprzedajemy cannabisu · tylko dla osób 18+ · używaj odpowiedzialnie",f_title:"Dodaj swój lokal do Brosin",f_intro:"Wpisz dane swojego klubu, grow shopu lub sklepu z CBD. Pojawienie się na mapie jest za darmo. Po wysłaniu trafiają prosto do nas i się z Tobą skontaktujemy.",f_note:"Niezbędne są nazwa, typ, miasto i adres. Reszta poprawia Twoją wizytówkę, ale może zostać pusta.",l_nombre:"Nazwa lokalu",l_tipo:"Typ",opt_elige:"Wybierz…",opt_csc:"Klub Społeczny Cannabis (CSC)",opt_grow:"Grow shop",opt_cbd:"Sklep z CBD",opt_coffee:"Coffeeshop",opt_med:"Medyczny",opt_emp:"Firma z branży",l_edad:"Wstęp tylko dla dorosłych?",opt_noind:"Nie podawaj",l_ciudad:"Miasto",l_prov:"Województwo",l_dir:"Pełny adres",l_tel:"Telefon / WhatsApp",l_email:"E-mail kontaktowy",l_horario:"Godziny otwarcia",l_redes:"Instagram / Strona www",l_desc:"Krótki opis",ph_nombre:"Np. Brosin CSC",ph_ciudad:"Np. Torre del Mar",ph_prov:"Np. Málaga",ph_dir:"Ulica, numer, kod pocztowy, miasto",ph_tel:"Np. 600 000 000",ph_email:"twojmail@przyklad.com",ph_horario:"Np. pon–sob 12:00–23:30",ph_redes:"Np. @twojklub lub twojastrona.pl",ph_desc:"Klimat, co oferujesz…",consent:"Jestem osobą odpowiedzialną za ten lokal i wyrażam zgodę na jego pojawienie się w Brosin z tymi danymi. Wiem, że w każdej chwili mogę poprosić o usunięcie, pisząc na hola@brosin.app.",btn:"Wyślij mój lokal do Brosin",sending:"Wysyłanie…",err:"Ups, coś poszło nie tak przy wysyłaniu. Spróbuj ponownie lub napisz do nas na hola@brosin.app.",legal_form:"Twoje dane są przetwarzane zgodnie z RGPD wyłącznie w celu obsługi Twojego zgłoszenia w Brosin. Administrator: Brosin · hola@brosin.app. Tylko +18.",ok_title:"Odebrane, bro!",ok_msg:"Mamy już Twój lokal. Rzucimy na niego okiem i skontaktujemy się, żeby dopracować go na mapie. Dzięki, że dołączasz do ula!"}
  };
  var LANGS=[["es","Español"],["en","English"],["de","Deutsch"],["fr","Français"],["nl","Nederlands"],["it","Italiano"],["pt","Português"],["sv","Svenska"],["pl","Polski"]];
  function cur(){var s;try{s=localStorage.getItem('brosin_lang');}catch(e){}if(s&&DICT[s])return s;var n=(navigator.language||navigator.userLanguage||'es').slice(0,2).toLowerCase();return DICT[n]?n:'es';}
  function t(k){var l=cur();return (DICT[l]&&DICT[l][k])||(DICT.es&&DICT.es[k])||'';}
  function apply(lang){
    document.documentElement.setAttribute('lang',lang);
    document.querySelectorAll('[data-i18n]').forEach(function(el){var v=(DICT[lang]&&DICT[lang][el.getAttribute('data-i18n')])||'';if(v)el.textContent=v;});
    document.querySelectorAll('[data-i18n-ph]').forEach(function(el){var v=(DICT[lang]&&DICT[lang][el.getAttribute('data-i18n-ph')])||'';if(v)el.setAttribute('placeholder',v);});
    var sel=document.getElementById('brosinLang');if(sel)sel.value=lang;
  }
  /* ---- Tema claro/oscuro (sol/luna) ---- */
  var SUN='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M19.1 4.9l-1.4 1.4M6.3 17.7l-1.4 1.4"/></svg>';
  var MOON='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z"/></svg>';
  function theme(){var t;try{t=localStorage.getItem('brosin_theme');}catch(e){}return t==='dark'?'dark':'light';}
  function paintTheme(){
    var t=theme();
    document.documentElement.setAttribute('data-theme',t);
    var tb=document.getElementById('brosinTheme');if(tb)tb.innerHTML=(t==='light'?MOON:SUN);
    var mc=document.querySelector('meta[name="theme-color"]');if(mc)mc.setAttribute('content',t==='light'?'#FFFFFF':'#0A0A0A');
  }
  function setTheme(t){try{localStorage.setItem('brosin_theme',t);}catch(e){}paintTheme();}

  /* ---- Controles: tema + idioma (arriba a la derecha) ---- */
  function selector(){
    if(document.getElementById('brosinCtrls'))return;
    var w=document.createElement('div');w.id='brosinCtrls';
    var tb=document.createElement('button');tb.id='brosinTheme';tb.type='button';tb.setAttribute('aria-label','Cambiar tema claro / oscuro');
    tb.addEventListener('click',function(){setTheme(theme()==='light'?'dark':'light');});
    w.appendChild(tb);
    var s=document.createElement('select');s.id='brosinLang';s.setAttribute('aria-label','Idioma / Language');
    LANGS.forEach(function(l){var o=document.createElement('option');o.value=l[0];o.textContent=l[1];s.appendChild(o);});
    s.addEventListener('change',function(){var v=s.value;try{localStorage.setItem('brosin_lang',v);}catch(e){}apply(v);});
    w.appendChild(s);
    document.body.appendChild(w);
    paintTheme();
  }
  function init(){selector();apply(cur());}
  window.BrosinI18n={t:t,apply:apply,lang:cur,theme:theme,setTheme:setTheme};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
