/* ===========================================================
   BASE DE DATOS DE LOCALES — BrosInCulture
   Edita aquí para añadir/quitar locales. La app los lee sola.
   tipo: 'csc' (club) · 'grow' · 'cbd'   |   brosin: true solo en locales Brosin
   =========================================================== */
window.CLUBS = [
  /* === COLMENA BROSIN === */
  {id:1, name:"Brosin", type:"csc", brosin:true, ccaa:"Andalucía", prov:"Málaga", city:"Torre del Mar", address:"Av. Doctor Marañón, 16, 29740 Torre del Mar, Málaga", lat:36.7405, lng:-4.0950, phone:"", hours:"Todos los días 12:00–23:30", verified:true, rating:0, reviews:0, tags:["Casa madre"], desc:"Donde nació Brosin en 2018. El origen y el corazón de la colmena. Más info en brosin.es", events:[]},
  {id:2, name:"DogRoom", type:"csc", brosin:true, ccaa:"Andalucía", prov:"Málaga", city:"Benalmádena", address:"Av. Federico García Lorca, 28, bloque F, 29631 Benalmádena, Málaga", lat:36.5987, lng:-4.5165, phone:"", hours:"Todos los días 12:00–00:00 · solo +21", verified:true, rating:3.5, reviews:19, tags:["+21"], desc:"Un espacio especial entre Arroyo de la Miel y Benalmádena. IG: @dogroomcsc", events:[]},
  {id:3, name:"Lighthouse", type:"csc", brosin:true, ccaa:"Andalucía", prov:"Málaga", city:"Torrox Costa", address:"Paseo marítimo, Torrox Costa, Málaga (dirección por confirmar)", lat:36.7290, lng:-3.9530, phone:"", hours:"", verified:true, rating:0, reviews:0, tags:["Frente al mar"], desc:"En pleno paseo marítimo, junto a un faro antiguo.", events:[]},
  {id:4, name:"El Submarino", type:"csc", brosin:true, ccaa:"Andalucía", prov:"Málaga", city:"Nerja", address:"C. Hibiscos, 29780 Nerja, Málaga", lat:36.7440, lng:-3.8770, phone:"", hours:"Todos los días 12:00–00:00 · solo +21", verified:true, rating:0, reviews:0, tags:["+21","Único"], desc:"Bajo la piscina: ventanas reales con miles de litros de agua sobre tu cabeza. IG: @elsubmarino.nerja", events:[]},
  {id:5, name:"Tropical Sexy", type:"csc", brosin:true, ccaa:"Andalucía", prov:"Granada", city:"Almuñécar", address:"Casco antiguo, Almuñécar, Granada (dirección por confirmar)", lat:36.7340, lng:-3.6920, phone:"", hours:"", verified:true, rating:0, reviews:0, tags:["Costa Tropical"], desc:"En pleno casco antiguo, a un minuto de la playa.", events:[]},
  {id:6, name:"La Casa 420", type:"csc", brosin:true, ccaa:"Andalucía", prov:"Málaga", city:"Algarrobo Costa", address:"Algarrobo-Costa, Málaga (primera línea de playa)", lat:36.7480, lng:-4.0420, phone:"", hours:"", verified:true, rating:5.0, reviews:10, tags:["Vistas al mar"], desc:"Local magnífico con vistas al mar. «Mi casa es tu casa». Valorado 5,0★ en Weedmaps.", events:[]},

  /* === ANDALUCÍA · grow & cbd === */
  {id:7, name:"An Glubuuu Grow Shop", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Málaga", city:"Torre del Mar", address:"Torre del Mar / Vélez-Málaga, Málaga (dirección por confirmar)", lat:36.7389, lng:-4.0970, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","Semillas"], desc:"Grow shop de la Axarquía.", events:[]},
  {id:8, name:"Sativa Grow Shop", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Málaga", city:"Vélez-Málaga", address:"Av. Vivar Téllez 95, Edif. Plaza (bajo), 29700 Vélez-Málaga, Málaga", lat:36.7820, lng:-4.1010, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop especializado en cultivo.", events:[]},
  {id:9, name:"Sativa Grow Shop (Nerja)", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Málaga", city:"Nerja", address:"Ctra. N-340, Edif. Armijo III, Local 2, 29780 Nerja, Málaga", lat:36.7510, lng:-3.8770, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Sede en Nerja de Sativa Grow Shop.", events:[]},
  {id:10, name:"Vivi Grow Shop", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Málaga", city:"Vélez-Málaga", address:"Camino del Remamente 7, 29700 Vélez-Málaga, Málaga", lat:36.7790, lng:-4.1040, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Vélez-Málaga.", events:[]},
  {id:11, name:"Tropical Grow Shop", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Granada", city:"Almuñécar", address:"C. Trinidad 21, 18690 Almuñécar, Granada", lat:36.7345, lng:-3.6905, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","Costa Tropical"], desc:"Grow shop en Almuñécar.", events:[]},
  {id:12, name:"Tropical Hemp", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Granada", city:"Motril", address:"C. Buenavista 1 (bajo), 18600 Motril, Granada", lat:36.7480, lng:-3.5180, phone:"958 603 087", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Motril.", events:[]},
  {id:13, name:"Mundogrow Motril", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Granada", city:"Motril", address:"Pl. de la Autonomía 10, 18600 Motril, Granada", lat:36.7470, lng:-3.5200, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en el centro de Motril.", events:[]},
  {id:14, name:"Mundo Grow (El Vadillo)", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Granada", city:"Motril", address:"Ctra. Almería 32, P.I. El Vadillo, 18600 Motril, Granada", lat:36.7560, lng:-3.5050, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Segunda sede de Mundo Grow.", events:[]},
  {id:15, name:"Grow Shop Granada All-in", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Granada", city:"Pulianas", address:"Ctra. de Güevejar 9, 18197 Pulianas, Granada", lat:37.2160, lng:-3.6080, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","A domicilio"], desc:"Grow shop en Granada con envío a domicilio.", events:[]},
  {id:16, name:"CBD Costa del Sol", type:"cbd", brosin:false, ccaa:"Andalucía", prov:"Málaga", city:"Torremolinos", address:"Av. Isabel Manoja 15, 29620 Torremolinos, Málaga", lat:36.6230, lng:-4.4990, phone:"674 880 334", hours:"Lun-Sáb 10:00–21:00", verified:false, rating:0, reviews:0, tags:["CBD","Envío 24h"], desc:"Tienda de CBD de referencia en la Costa del Sol.", events:[]},
  {id:17, name:"Greenery 420 CBD", type:"cbd", brosin:false, ccaa:"Andalucía", prov:"Málaga", city:"Marbella", address:"C. Ntra. Sra. de Gracia 7, Local 4, 29602 Marbella, Málaga", lat:36.5100, lng:-4.8855, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Flores","Aceites"], desc:"Tienda CBD en Marbella.", events:[]},
  {id:18, name:"Buenahierba", type:"cbd", brosin:false, ccaa:"Andalucía", prov:"Málaga", city:"Fuengirola", address:"P.º Jesús Santos Rein 17, 29640 Fuengirola, Málaga", lat:36.5395, lng:-4.6250, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en Fuengirola.", events:[]},
  {id:19, name:"420 Growshop Sevilla", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Sevilla", city:"Sevilla", address:"C. Páez de Rivera, Local 4, Sevilla", lat:37.3530, lng:-5.9850, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Sevilla.", events:[]},
  {id:20, name:"THC Sevilla Distribuciones", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Sevilla", city:"Sevilla", address:"C. Escarpia 72, 41007 Sevilla", lat:37.3960, lng:-5.9560, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","Distribución"], desc:"Grow shop y distribución en Sevilla.", events:[]},
  {id:21, name:"Grand Poison Grow Shop", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Sevilla", city:"Camas", address:"Cam. Empedrado 17, 41900 Camas, Sevilla", lat:37.3920, lng:-6.0350, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Camas (Sevilla).", events:[]},
  {id:22, name:"Sativida CBD", type:"cbd", brosin:false, ccaa:"Andalucía", prov:"Sevilla", city:"Sevilla", address:"C. Jaén 2, 41001 Sevilla", lat:37.3870, lng:-5.9920, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en el centro de Sevilla.", events:[]},
  {id:23, name:"Tu Yerba CBD", type:"cbd", brosin:false, ccaa:"Andalucía", prov:"Sevilla", city:"Sevilla", address:"C. San Eloy 37, 41001 Sevilla", lat:37.3905, lng:-5.9970, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en San Eloy, Sevilla.", events:[]},
  {id:24, name:"CBDONIA", type:"cbd", brosin:false, ccaa:"Andalucía", prov:"Sevilla", city:"Sevilla", address:"C. Demetrio de los Ríos 7, 41003 Sevilla", lat:37.3850, lng:-5.9870, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"CBD shop en Sevilla.", events:[]},
  {id:25, name:"CBD Crysálidas", type:"cbd", brosin:false, ccaa:"Andalucía", prov:"Sevilla", city:"Sevilla", address:"C. Trajano 52, bajo, 41002 Sevilla", lat:37.3935, lng:-5.9930, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en el Casco Antiguo de Sevilla.", events:[]},
  {id:26, name:"Cibidy CBD", type:"cbd", brosin:false, ccaa:"Andalucía", prov:"Sevilla", city:"Sevilla", address:"C/ Valle 2, 41003 Sevilla", lat:37.3880, lng:-5.9860, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"CBD Seville, Casco Antiguo.", events:[]},
  {id:27, name:"CBWeed Sevilla", type:"cbd", brosin:false, ccaa:"Andalucía", prov:"Sevilla", city:"Sevilla", address:"C. Puente y Pellón 5, 41004 Sevilla", lat:37.3905, lng:-5.9890, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en Sevilla.", events:[]},
  {id:28, name:"Green Money Grow Shop", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Cádiz", city:"Jerez de la Frontera", address:"C. Ducado (Ciudad del Transporte, Zona II), Jerez de la Frontera, Cádiz", lat:36.6850, lng:-6.0950, phone:"956 254 040", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Jerez de la Frontera.", events:[]},
  {id:29, name:"La Caña de María", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Cádiz", city:"Jerez de la Frontera", address:"Av. de Arcos, Pol. Naviarcos, nave 14, 11406 Jerez de la Frontera, Cádiz", lat:36.7050, lng:-6.1100, phone:"665 818 963", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Jerez de la Frontera.", events:[]},
  {id:30, name:"GB The Green Brand Córdoba", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Córdoba", city:"Córdoba", address:"C. los Metalúrgicos 86P, Pol. Pedroches, Córdoba", lat:37.9170, lng:-4.7720, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","Semillas"], desc:"Grow shop de la cadena GB en Córdoba.", events:[]},
  {id:31, name:"Dr. Cogollo", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Córdoba", city:"Córdoba", address:"Córdoba (dirección por confirmar)", lat:37.8880, lng:-4.7790, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD","Head shop"], desc:"CBD shop, grow shop y head shop en Córdoba desde 2001.", events:[]},
  {id:32, name:"Green Factory Grow Shop", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Almería", city:"Almería", address:"C. Leandro Fernández de Moratín 2, 04007 Almería", lat:36.8430, lng:-2.4520, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","Semillas"], desc:"Grow shop de autocultivo en Almería.", events:[]},
  {id:33, name:"Loto Verde Grow Shop", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Almería", city:"Almería", address:"C. Rubí 38, Almería", lat:36.8390, lng:-2.4480, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Almería.", events:[]},
  {id:34, name:"Grow Shop La Cañada", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Almería", city:"La Cañada", address:"C. Nepal 4, 04120 La Cañada, Almería", lat:36.8290, lng:-2.4030, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD en La Cañada (Almería).", events:[]},
  {id:35, name:"Tienda CBD · Almería centro", type:"cbd", brosin:false, ccaa:"Andalucía", prov:"Almería", city:"Almería", address:"C. Concepción Arenal 6, 04001 Almería", lat:36.8400, lng:-2.4670, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Vapeo"], desc:"Tienda de CBD y vapeo en Almería.", events:[]},
  {id:36, name:"Tienda CBD · Aguadulce", type:"cbd", brosin:false, ccaa:"Andalucía", prov:"Almería", city:"Almería", address:"C. Santiago Vergara 46, 04008 Almería", lat:36.8350, lng:-2.4750, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en Almería.", events:[]},
  {id:37, name:"La Grow de Huelva", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Huelva", city:"Huelva", address:"Ctra. Gibraleón, 21005 Huelva", lat:37.2670, lng:-6.9560, phone:"", hours:"Lun-Vie 10:00–20:00", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Huelva.", events:[]},
  {id:38, name:"La Cabra Verde Grow & Vape", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Jaén", city:"Úbeda", address:"C. Alonso de Molina 6, bajo, 23400 Úbeda, Jaén", lat:38.0130, lng:-3.3700, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","Vapeo"], desc:"Grow shop y vape shop en Úbeda (Jaén).", events:[]},
  {id:39, name:"Sinsemillast Street Grow Shop", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Málaga", city:"Málaga", address:"Málaga centro (dirección por confirmar)", lat:36.7200, lng:-4.4200, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en el centro de Málaga, +20 años.", events:[]},
  {id:40, name:"García Grow Shop", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Málaga", city:"Benalmádena", address:"C/ Los Cármenes 6, Benalmádena, Málaga", lat:36.5980, lng:-4.5160, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop, cannabis, CBD y HHC en Benalmádena.", events:[]},
  {id:41, name:"MatillaPlant Grow Shop", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Granada", city:"Granada", address:"C. Diamantino García 1, Zaidín, 18007 Granada", lat:37.1640, lng:-3.6060, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","Semillas"], desc:"Grow shop en Granada (Zaidín).", events:[]},

  /* === MADRID === */
  {id:42, name:"Houseplant Madrid", type:"grow", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Madrid", address:"C. de la Palma 42, 28004 Madrid", lat:40.4258, lng:-3.7060, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Malasaña (Madrid).", events:[]},
  {id:43, name:"El Oro Verde", type:"grow", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Madrid", address:"C. de San Vicente Ferrer 14, 28004 Madrid", lat:40.4250, lng:-3.7030, phone:"", hours:"Lun-Sáb 11:30–21:00", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en el centro de Madrid.", events:[]},
  {id:44, name:"Growland Growshop", type:"grow", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Madrid", address:"C. Lope de Haro 5, Tetuán, Madrid", lat:40.4570, lng:-3.6980, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Tetuán.", events:[]},
  {id:45, name:"Cultura Cannábica", type:"grow", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Madrid", address:"Pl. de Cascorro 1, 28005 Madrid", lat:40.4090, lng:-3.7060, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD en el Rastro.", events:[]},
  {id:46, name:"CBD Madrid", type:"cbd", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Madrid", address:"C. La Palma 53, 28004 Madrid", lat:40.4262, lng:-3.7050, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Flores","Aceites"], desc:"Tienda de CBD en el centro de Madrid.", events:[]},
  {id:47, name:"Kenke Corner CBD", type:"cbd", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Madrid", address:"Vallecas, Madrid (dirección por confirmar)", lat:40.3920, lng:-3.6650, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Flores","Resinas"], desc:"Tienda de CBD en Vallecas.", events:[]},
  {id:48, name:"Mr. Weed CBD Shop", type:"cbd", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Madrid", address:"Madrid Centro (dirección por confirmar)", lat:40.4150, lng:-3.7020, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en el centro de Madrid.", events:[]},

  /* === CATALUÑA === */
  {id:49, name:"Zona de Cultivo", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Barcelona", address:"Carrer de Vilamarí 65, 08015 Barcelona", lat:41.3790, lng:2.1530, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","Semillas"], desc:"Grow shop en Barcelona (Sants).", events:[]},
  {id:50, name:"Grow Shop Barcelona", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Barcelona", address:"C/ Felipe II 207, Barcelona", lat:41.4230, lng:2.1810, phone:"93 408 50 08", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Barcelona.", events:[]},
  {id:51, name:"House Plant Grow Shop BCN", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Barcelona", address:"Carrer de Casanova 34, 08011 Barcelona", lat:41.3820, lng:2.1610, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en el Eixample.", events:[]},
  {id:52, name:"Under Grow BCN", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Barcelona", address:"Carrer dels Tallers 10, 08001 Barcelona", lat:41.3845, lng:2.1690, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en el centro de Barcelona.", events:[]},
  {id:53, name:"Sensitive CBD", type:"cbd", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Barcelona", address:"Carrer de Floridablanca 132, 08015 Barcelona", lat:41.3800, lng:2.1570, phone:"937 828 275", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en Barcelona.", events:[]},
  {id:54, name:"La Catalana CBD", type:"cbd", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Barcelona", address:"Consell de Cent 344, 08009 Barcelona", lat:41.3920, lng:2.1640, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en el Eixample.", events:[]},
  {id:55, name:"CBD Undercity", type:"cbd", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Santa Coloma de Gramenet", address:"Santa Coloma 74, 08922 Santa Coloma de Gramenet, Barcelona", lat:41.4520, lng:2.2080, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en Santa Coloma.", events:[]},

  /* === C. VALENCIANA === */
  {id:56, name:"Grow Shop Més Que Brossa", type:"grow", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"València", address:"Carrer de l'Enginyer Manuel Maese 15, 46011 València", lat:39.4590, lng:-0.3310, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Valencia.", events:[]},
  {id:57, name:"The Cannabis Shop Valencia", type:"grow", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"València", address:"C/ dels Cordellats 6, Ciutat Vella, 46001 València", lat:39.4730, lng:-0.3770, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en el centro de Valencia.", events:[]},
  {id:58, name:"Grow Shop Valencia GVB", type:"grow", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"València", address:"C/ de Pere Cabanes 4, 46019 Valencia", lat:39.4880, lng:-0.3580, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD en Valencia.", events:[]},
  {id:59, name:"Echando Raíces Grow & CBD", type:"grow", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"Alfafar", address:"Av. Gómez Ferrer 35, bajo izq, 46910 Alfafar, Valencia", lat:39.4200, lng:-0.3870, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD en Alfafar.", events:[]},
  {id:60, name:"Cogolandia", type:"grow", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"Xàtiva", address:"Pol. Ind. C, Calle Proyecto 3, 46800 Xàtiva, Valencia", lat:38.9870, lng:-0.5180, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Xàtiva.", events:[]},
  {id:76, name:"Greenery 420 CBD Alicante", type:"cbd", brosin:false, ccaa:"C. Valenciana", prov:"Alicante", city:"Alicante", address:"Av. Óscar Esplá 22, 03003 Alicante", lat:38.3470, lng:-0.4870, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Flores","Aceites"], desc:"Tienda de CBD premium en Alicante.", events:[]},
  {id:77, name:"Pura Terreta", type:"grow", brosin:false, ccaa:"C. Valenciana", prov:"Alicante", city:"Alicante", address:"Alicante (dirección por confirmar)", lat:38.3460, lng:-0.4900, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","Ecológico"], desc:"Grow shop de cultivo ecológico en Alicante desde 2008.", events:[]},

  /* === PAÍS VASCO === */
  {id:61, name:"Ecologic Grow Shop", type:"grow", brosin:false, ccaa:"País Vasco", prov:"Bizkaia", city:"Bilbao", address:"Sabino Arana Etorbidea 40, 48013 Bilbao, Bizkaia", lat:43.2620, lng:-2.9450, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","Semillas"], desc:"Grow shop de confianza en Bilbao.", events:[]},
  {id:62, name:"Sadhu Growshop", type:"grow", brosin:false, ccaa:"País Vasco", prov:"Bizkaia", city:"Barakaldo", address:"Kareaga 67, nave 8, Barakaldo, Bizkaia", lat:43.2960, lng:-2.9890, phone:"944 97 86 33", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Barakaldo.", events:[]},
  {id:63, name:"Cannabis Shop Bilbao", type:"grow", brosin:false, ccaa:"País Vasco", prov:"Bizkaia", city:"Bilbao", address:"C/ Ibarrekolanda 36, lonja, Bilbao", lat:43.2710, lng:-2.9560, phone:"637 733 677", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Bilbao.", events:[]},

  /* === ARAGÓN === */
  {id:64, name:"Bajo el Sol", type:"grow", brosin:false, ccaa:"Aragón", prov:"Zaragoza", city:"Zaragoza", address:"C/ San Antonio María Claret 62, 50005 Zaragoza", lat:41.6390, lng:-0.8950, phone:"976 566 672", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Zaragoza.", events:[]},
  {id:65, name:"CANNA Store Zaragoza", type:"grow", brosin:false, ccaa:"Aragón", prov:"Zaragoza", city:"Zaragoza", address:"C/ Mosén Damián Borobia 12, local dcha, 50016 Zaragoza", lat:41.6630, lng:-0.8680, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD en Zaragoza.", events:[]},

  /* === GALICIA === */
  {id:66, name:"Diosa Planta", type:"grow", brosin:false, ccaa:"Galicia", prov:"A Coruña", city:"A Coruña", address:"Rúa Galileo Galilei 48, bajo, 15008 A Coruña", lat:43.3360, lng:-8.4100, phone:"981 24 30 49", hours:"Lun-Sáb", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD","Semillas"], desc:"Grow shop y CBD en A Coruña.", events:[]},
  {id:82, name:"Herbalist Grow Shop", type:"grow", brosin:false, ccaa:"Galicia", prov:"Pontevedra", city:"Vigo", address:"Trav. de Vigo 186, bajo, 36207 Vigo, Pontevedra", lat:42.2280, lng:-8.7020, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Vigo.", events:[]},
  {id:83, name:"Cañamazo Vigo", type:"grow", brosin:false, ccaa:"Galicia", prov:"Pontevedra", city:"Vigo", address:"Av. da Florida 183, bajo, 36213 Vigo, Pontevedra", lat:42.2160, lng:-8.7290, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","Semillas"], desc:"Grow shop en Vigo.", events:[]},
  {id:84, name:"Grow Shop Ourense", type:"grow", brosin:false, ccaa:"Galicia", prov:"Ourense", city:"Ourense", address:"C. Manzaneda 17, bajo, 32005 Ourense", lat:42.3380, lng:-7.8640, phone:"988 222 327", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Ourense.", events:[]},
  {id:85, name:"Grow Shop Pontevedra", type:"grow", brosin:false, ccaa:"Galicia", prov:"Pontevedra", city:"Pontevedra", address:"Avda. Montecelo 22, 36161 Pontevedra", lat:42.4380, lng:-8.6020, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Pontevedra.", events:[]},

  /* === MURCIA === */
  {id:67, name:"The Tree CBD", type:"cbd", brosin:false, ccaa:"Región de Murcia", prov:"Murcia", city:"Cartagena", address:"C. Sierra Espuña, 30310 Cartagena, Murcia", lat:37.6260, lng:-0.9960, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Flores"], desc:"Tienda premium de CBD en Cartagena.", events:[]},
  {id:68, name:"Submarine Vape", type:"cbd", brosin:false, ccaa:"Región de Murcia", prov:"Murcia", city:"Cartagena", address:"Plaza Juan XXIII, Local 5, 30201 Cartagena, Murcia", lat:37.6080, lng:-0.9880, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Vapeo"], desc:"Vapeo y productos CBD en Cartagena.", events:[]},
  {id:78, name:"La Catalana CBD · Murcia", type:"cbd", brosin:false, ccaa:"Región de Murcia", prov:"Murcia", city:"Murcia", address:"C. Ceballos 6, 30001 Murcia", lat:37.9840, lng:-1.1300, phone:"648 239 987", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Punto de venta de CBD en Murcia.", events:[]},

  /* === CANARIAS === */
  {id:69, name:"La Milla Verde Grow Shop", type:"grow", brosin:false, ccaa:"Canarias", prov:"Las Palmas", city:"Ingenio", address:"Calle Teide 21, Carrizal, Ingenio, Gran Canaria", lat:27.9200, lng:-15.4300, phone:"928 509 622", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD en Gran Canaria.", events:[]},
  {id:79, name:"Grow Shop Canarias", type:"grow", brosin:false, ccaa:"Canarias", prov:"Las Palmas", city:"Arrecife", address:"C. José Viera y Clavijo 3, 35500 Arrecife, Las Palmas", lat:28.9630, lng:-13.5500, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","Semillas"], desc:"Expertos en cultivo en Lanzarote.", events:[]},
  {id:80, name:"Línea Verde Grow Shop", type:"grow", brosin:false, ccaa:"Canarias", prov:"Las Palmas", city:"Gran Tarajal", address:"C. Vigán 7, bajo, 35620 Gran Tarajal, Las Palmas", lat:28.2090, lng:-14.0180, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Fuerteventura.", events:[]},
  {id:81, name:"Santa Grow Shop", type:"grow", brosin:false, ccaa:"Canarias", prov:"Santa Cruz de Tenerife", city:"Santa Cruz de Tenerife", address:"Santa Cruz de Tenerife (dirección por confirmar)", lat:28.4680, lng:-16.2520, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Tenerife con envío a todas las islas.", events:[]},

  /* === BALEARES === */
  {id:70, name:"Mallorca Indoors Grow Shop", type:"grow", brosin:false, ccaa:"Illes Balears", prov:"Illes Balears", city:"Palma", address:"Carrer Gremi Teixidors 35, 07009 Palma, Illes Balears", lat:39.5950, lng:-2.6900, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Palma de Mallorca.", events:[]},

  /* === CASTILLA Y LEÓN === */
  {id:71, name:"Terpeno Maldito", type:"grow", brosin:false, ccaa:"Castilla y León", prov:"Valladolid", city:"Valladolid", address:"C/ Cobalto 11, Valladolid", lat:41.6400, lng:-4.7250, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Valladolid.", events:[]},
  {id:72, name:"Santy Erbasi", type:"grow", brosin:false, ccaa:"Castilla y León", prov:"Valladolid", city:"Valladolid", address:"Calle Plata 12, Nave 3, Pol. San Cristóbal, 47012 Valladolid", lat:41.6200, lng:-4.7100, phone:"983 307 656", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Valladolid.", events:[]},
  {id:73, name:"Natura Vice", type:"grow", brosin:false, ccaa:"Castilla y León", prov:"Valladolid", city:"Valladolid", address:"Pz. Circular 8, 47005 Valladolid", lat:41.6480, lng:-4.7330, phone:"983 119 535", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en el centro de Valladolid.", events:[]},

  /* === ASTURIAS === */
  {id:74, name:"Mar Verde", type:"grow", brosin:false, ccaa:"Asturias", prov:"Asturias", city:"Oviedo", address:"C/ Hermanas Sánchez Tamargo 2, Pol. Ferreros, 33012 Oviedo, Asturias", lat:43.3600, lng:-5.8600, phone:"985 084 750", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Oviedo.", events:[]},
  {id:75, name:"Total Grow Shop", type:"grow", brosin:false, ccaa:"Asturias", prov:"Asturias", city:"Gijón", address:"C/ Marie Curie 32, Pol. Mora Garay, 33211 Gijón, Asturias", lat:43.5200, lng:-5.6400, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Gijón.", events:[]},

  /* === NAVARRA / LA RIOJA / CANTABRIA === */
  {id:86, name:"Marea Verde", type:"grow", brosin:false, ccaa:"Navarra", prov:"Navarra", city:"Pamplona", address:"Avda. Zaragoza 29, bajo, 31005 Pamplona, Navarra", lat:42.8030, lng:-1.6520, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Pamplona.", events:[]},
  {id:87, name:"Yerba Buena", type:"grow", brosin:false, ccaa:"La Rioja", prov:"La Rioja", city:"Logroño", address:"Avda. Mendavia 37, Local 3, 26006 Logroño, La Rioja", lat:42.4600, lng:-2.4700, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD en Logroño.", events:[]},
  {id:88, name:"Grow Shop Santander", type:"grow", brosin:false, ccaa:"Cantabria", prov:"Cantabria", city:"Santander", address:"Pol. de Raos, parcela H, nave 32, 39600 Santander, Cantabria", lat:43.4050, lng:-3.8500, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Santander.", events:[]},

  /* === MÁLAGA capital (CBD) === */
  {id:89, name:"CBD Store Málaga", type:"cbd", brosin:false, ccaa:"Andalucía", prov:"Málaga", city:"Málaga", address:"C. Martínez Maldonado 89, 29010 Málaga", lat:36.7250, lng:-4.4280, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Flores","Aceites"], desc:"Tienda de CBD de confianza en Málaga.", events:[]},
  {id:90, name:"WeedLab CBD", type:"cbd", brosin:false, ccaa:"Andalucía", prov:"Málaga", city:"Málaga", address:"C. Echegaray 3, 29015 Málaga", lat:36.7200, lng:-4.4180, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Flores","Cosmética"], desc:"CBD, flores, aceites y cosmética en el centro de Málaga.", events:[]},
  {id:91, name:"De Pata Verde", type:"cbd", brosin:false, ccaa:"Andalucía", prov:"Málaga", city:"Málaga", address:"Alameda de Colón 18, 29001 Málaga", lat:36.7170, lng:-4.4220, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Envío rápido"], desc:"Tienda de CBD en Málaga con entregas rápidas.", events:[]},

  /* === CATALUÑA (Lleida, Girona, Tarragona) === */
  {id:92, name:"Natural & CBD", type:"cbd", brosin:false, ccaa:"Cataluña", prov:"Lleida", city:"Lleida", address:"Plaça de Sant Joan 12, Lleida", lat:41.6170, lng:0.6200, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Flores","Aceites"], desc:"CBD, flores y cosmética junto al Eix Comercial de Lleida.", events:[]},
  {id:93, name:"Vilua Grow Shop", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Lleida", city:"Lleida", address:"Carrer Caldereries 9, Lleida", lat:41.6150, lng:0.6260, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Lleida.", events:[]},
  {id:94, name:"GrowBarato Lleida", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Lleida", city:"Lleida", address:"Avinguda de València 32, Lleida", lat:41.6080, lng:0.6300, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","Semillas"], desc:"Grow shop de la cadena GrowBarato en Lleida.", events:[]},
  {id:95, name:"Oasis CBD Store", type:"cbd", brosin:false, ccaa:"Cataluña", prov:"Lleida", city:"Lleida", address:"Carrer Democràcia 3, Lleida", lat:41.6160, lng:0.6230, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en Lleida.", events:[]},
  {id:96, name:"The Maria Shop", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Girona", city:"Figueres", address:"C/ Méndez Núñez 32, Local 12, 17600 Figueres, Girona", lat:42.2660, lng:2.9620, phone:"972 505 148", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD en Figueres (Girona).", events:[]},
  {id:97, name:"Zero Zero Grow", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Girona", city:"Vulpellac", address:"C/ Arboços 10, Nave 3, 17111 Vulpellac, Girona", lat:41.9430, lng:3.0700, phone:"972 644 865", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en el Baix Empordà (Girona).", events:[]},
  {id:98, name:"Grow Shop Torredembarra", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Tarragona", city:"Torredembarra", address:"C/ Lleida 4 bajos, 43830 Torredembarra, Tarragona", lat:41.1450, lng:1.3980, phone:"977 645 754", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Torredembarra (Tarragona).", events:[]},
  {id:99, name:"Grow Shop Salou", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Tarragona", city:"Salou", address:"Av. Carles Buïgas 24, 43840 Salou, Tarragona", lat:41.0760, lng:1.1410, phone:"977 382 987", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Salou (Tarragona).", events:[]},

  /* === C. VALENCIANA (Castellón, Alicante, Valencia) === */
  {id:100, name:"Dr. Cogollo Castellón", type:"grow", brosin:false, ccaa:"C. Valenciana", prov:"Castellón", city:"Castellón de la Plana", address:"Av. Rey Don Jaime 43 bajo, 12001 Castellón", lat:39.9870, lng:-0.0370, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD en Castellón.", events:[]},
  {id:101, name:"Tecnocultivo Castellón", type:"grow", brosin:false, ccaa:"C. Valenciana", prov:"Castellón", city:"Castellón de la Plana", address:"Rambla de la Viuda, nave 3, Castellón", lat:39.9900, lng:-0.0510, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Castellón.", events:[]},
  {id:102, name:"Grow Shops Jardala", type:"grow", brosin:false, ccaa:"C. Valenciana", prov:"Alicante", city:"Elche", address:"Teniente Andrés Estellés 12, 03202 Elche, Alicante", lat:38.2690, lng:-0.7000, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Elche.", events:[]},
  {id:103, name:"Growshop Elche", type:"grow", brosin:false, ccaa:"C. Valenciana", prov:"Alicante", city:"Crevillente", address:"Pol. Ind. Faima 10, nave 2, c/ Ondara, 03330 Crevillente, Alicante", lat:38.2480, lng:-0.8100, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop Elche / Petrer.", events:[]},
  {id:104, name:"Mundo Ganja Grow Shop", type:"grow", brosin:false, ccaa:"C. Valenciana", prov:"Alicante", city:"Alicante", address:"C. Espoz y Mina 6, 03012 Alicante", lat:38.3520, lng:-0.4830, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Alicante.", events:[]},
  {id:105, name:"FlorProhibida Grow Shop", type:"grow", brosin:false, ccaa:"C. Valenciana", prov:"Alicante", city:"Alicante", address:"C. Teulada 20, 03009 Alicante", lat:38.3650, lng:-0.4950, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Alicante.", events:[]},
  {id:106, name:"CBD'Horta", type:"cbd", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"València", address:"C/ Santa Genoveva Torres 30, bajo, València", lat:39.4860, lng:-0.3620, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Flores"], desc:"Tienda de CBD en Valencia.", events:[]},
  {id:107, name:"Family Tree CBD", type:"cbd", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"València", address:"C. Reverendo José María Pinazo 14, Bajo 3, Benimaclet, València", lat:39.4870, lng:-0.3580, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Cannabis boutique y CBD en Benimaclet (Valencia).", events:[]},
  {id:108, name:"Sensitive CBD Valencia", type:"cbd", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"València", address:"C. Cuba 29, Ruzafa, València", lat:39.4620, lng:-0.3760, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en Ruzafa (Valencia).", events:[]},

  /* === CÁDIZ === */
  {id:109, name:"Grow Shop El Bosque Verde", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Cádiz", city:"Algeciras", address:"Avenida Caña 31, Algeciras, Cádiz", lat:36.1330, lng:-5.4500, phone:"622 428 378", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Algeciras (Cádiz).", events:[]},
  {id:110, name:"Lisergia Grow Shop", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Cádiz", city:"Sanlúcar de Barrameda", address:"Ctra. Sanlúcar-Chipiona, Pol. las Palmeras, c/ Algarrobo 5, 11540 Sanlúcar de Barrameda, Cádiz", lat:36.7600, lng:-6.3300, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Sanlúcar de Barrameda (Cádiz).", events:[]},

  /* === CASTILLA-LA MANCHA === */
  {id:111, name:"GM Grow Shop", type:"grow", brosin:false, ccaa:"Castilla-La Mancha", prov:"Toledo", city:"Toledo", address:"Pol. Ind. Sta. María de Benquerencia, C. Río Jarama 132, Nave 9.02, 45007 Toledo", lat:39.8590, lng:-3.9560, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Toledo.", events:[]},
  {id:112, name:"FlorProhibida Albacete", type:"grow", brosin:false, ccaa:"Castilla-La Mancha", prov:"Albacete", city:"Albacete", address:"Av. Gregorio Arcos 56, 02007 Albacete", lat:38.9940, lng:-1.8580, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Tienda física de FlorProhibida en Albacete.", events:[]},

  /* === EXTREMADURA === */
  {id:113, name:"Verde que te Quiero Verde", type:"grow", brosin:false, ccaa:"Extremadura", prov:"Badajoz", city:"Badajoz", address:"C. Vicente Delgado Algaba 92, 06010 Badajoz", lat:38.8830, lng:-6.9760, phone:"", hours:"Lun-Vie 10:00–14:00 y 17:00–21:00, Sáb 10:00–14:00", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD","Semillas"], desc:"Grow shop y CBD de referencia en Badajoz: semillas, flores CBD, aceites y parafernalia.", events:[]},
  {id:114, name:"Babylon GrowShop", type:"grow", brosin:false, ccaa:"Extremadura", prov:"Badajoz", city:"Badajoz", address:"Badajoz (dirección por confirmar)", lat:38.8790, lng:-6.9700, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD medicinal en Badajoz.", events:[]},
  {id:115, name:"Tienda CBD · Santa Marina (Badajoz)", type:"cbd", brosin:false, ccaa:"Extremadura", prov:"Badajoz", city:"Badajoz", address:"Av. Santa Marina 2, 06005 Badajoz", lat:38.8810, lng:-6.9650, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en Badajoz.", events:[]},
  {id:116, name:"Renovatio Vapor (Av. Portugal)", type:"cbd", brosin:false, ccaa:"Extremadura", prov:"Cáceres", city:"Cáceres", address:"Av. de Portugal 2, Local 11, 10001 Cáceres", lat:39.4730, lng:-6.3760, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Vapeo"], desc:"CBD y vapeo en Cáceres.", events:[]},
  {id:117, name:"Renovatio Vapor (San Pedro)", type:"cbd", brosin:false, ccaa:"Extremadura", prov:"Cáceres", city:"Cáceres", address:"C. San Pedro 4, local 7, 10003 Cáceres", lat:39.4720, lng:-6.3690, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Vapeo"], desc:"Segunda tienda Renovatio en Cáceres.", events:[]},

  /* === PAÍS VASCO (Gipuzkoa / Álava) === */
  {id:118, name:"The North Haze", type:"grow", brosin:false, ccaa:"País Vasco", prov:"Gipuzkoa", city:"Donostia-San Sebastián", address:"Donostia-San Sebastián (dirección por confirmar)", lat:43.3180, lng:-1.9810, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en el corazón de Donostia.", events:[]},
  {id:119, name:"Ganjah Grow Shop", type:"grow", brosin:false, ccaa:"País Vasco", prov:"Gipuzkoa", city:"Donostia-San Sebastián", address:"Altza, Donostia-San Sebastián, Gipuzkoa (dirección por confirmar)", lat:43.3260, lng:-1.9460, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","Semillas"], desc:"Grow shop y semillas en Altza (Donostia).", events:[]},
  {id:120, name:"Happy Garden Grow", type:"grow", brosin:false, ccaa:"País Vasco", prov:"Álava", city:"Vitoria-Gasteiz", address:"C/ Basoa 14, 01012 Vitoria-Gasteiz, Álava", lat:42.8580, lng:-2.6900, phone:"945 24 09 67", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Vitoria-Gasteiz.", events:[]},
  {id:121, name:"Bio Vitoria", type:"grow", brosin:false, ccaa:"País Vasco", prov:"Álava", city:"Vitoria-Gasteiz", address:"Avda. Santiago 6, 01002 Vitoria-Gasteiz, Álava", lat:42.8470, lng:-2.6760, phone:"945 120 004", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Vitoria-Gasteiz.", events:[]},

  /* === CASTILLA Y LEÓN (Burgos, Salamanca) === */
  {id:122, name:"Total CBD Burgos", type:"cbd", brosin:false, ccaa:"Castilla y León", prov:"Burgos", city:"Burgos", address:"C/ Sombrería 27, Burgos", lat:42.3405, lng:-3.7015, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Flores","Aceites"], desc:"Tienda de CBD en el centro de Burgos.", events:[]},
  {id:123, name:"Total CBD (Gamonal)", type:"cbd", brosin:false, ccaa:"Castilla y León", prov:"Burgos", city:"Burgos", address:"Plaza de Roma 10, Gamonal, Burgos", lat:42.3530, lng:-3.6680, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Segunda tienda Total CBD en Gamonal (Burgos).", events:[]},
  {id:124, name:"Native Growshop", type:"grow", brosin:false, ccaa:"Castilla y León", prov:"Burgos", city:"Burgos", address:"Burgos (dirección por confirmar)", lat:42.3400, lng:-3.7050, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD","Semillas"], desc:"Grow shop y CBD en Burgos: semillas, sustrato, fertilizantes y autocultivo.", events:[]},
  {id:125, name:"Topgrow Salamanca", type:"grow", brosin:false, ccaa:"Castilla y León", prov:"Salamanca", city:"Salamanca", address:"Salamanca (dirección por confirmar)", lat:40.9650, lng:-5.6640, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD local en Salamanca.", events:[]},

  /* === ISLAS BALEARES === */
  {id:126, name:"Growzone Mallorca", type:"grow", brosin:false, ccaa:"Illes Balears", prov:"Illes Balears", city:"Palma", address:"Centro de Palma de Mallorca (dirección por confirmar)", lat:39.5750, lng:2.6520, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","Jardinería"], desc:"El grow shop más grande de Mallorca.", events:[]},
  {id:127, name:"Grow Shop Ibiza (CANNA)", type:"grow", brosin:false, ccaa:"Illes Balears", prov:"Illes Balears", city:"Eivissa", address:"C. Navarra 32, bajo, 07800 Eivissa (Ibiza)", lat:38.9090, lng:1.4320, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Punto de cultivo y CBD en Ibiza.", events:[]},
  {id:128, name:"Grow Shop Campos", type:"grow", brosin:false, ccaa:"Illes Balears", prov:"Illes Balears", city:"Campos", address:"Ronda de Catalunya 31, 07630 Campos, Mallorca", lat:39.4310, lng:3.0170, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Campos (Mallorca).", events:[]},

  /* === CANARIAS capitales (CBD) === */
  {id:129, name:"Natural Weed Las Palmas", type:"cbd", brosin:false, ccaa:"Canarias", prov:"Las Palmas", city:"Las Palmas de Gran Canaria", address:"C. Tenerife 12, 35008 Las Palmas de Gran Canaria", lat:28.1330, lng:-15.4320, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Flores"], desc:"Tienda de CBD en Las Palmas de Gran Canaria.", events:[]},
  {id:130, name:"Greenery 420 CBD Canarias", type:"cbd", brosin:false, ccaa:"Canarias", prov:"Las Palmas", city:"Las Palmas de Gran Canaria", address:"C. Sagasta (centro), Las Palmas de Gran Canaria", lat:28.1290, lng:-15.4360, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Flores","Aceites"], desc:"Tienda Greenery de CBD en el centro de Las Palmas.", events:[]},
  {id:131, name:"La Tía María (Maspalomas)", type:"cbd", brosin:false, ccaa:"Canarias", prov:"Las Palmas", city:"Maspalomas", address:"Av. de Moya 10, local 1005-1006, 35100 Maspalomas, Las Palmas", lat:27.7610, lng:-15.5860, phone:"", hours:"Lun-Sáb 9:30–19:00", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en Maspalomas (Gran Canaria).", events:[]},
  {id:132, name:"CBD Store Santa Cruz", type:"cbd", brosin:false, ccaa:"Canarias", prov:"Santa Cruz de Tenerife", city:"Santa Cruz de Tenerife", address:"Calle Pi y Margall 8, Santa Cruz de Tenerife", lat:28.4710, lng:-16.2470, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en Santa Cruz de Tenerife.", events:[]},
  {id:133, name:"Tienda CBD · San Lucas (Tenerife)", type:"cbd", brosin:false, ccaa:"Canarias", prov:"Santa Cruz de Tenerife", city:"Santa Cruz de Tenerife", address:"C. de San Lucas 22, 38003 Santa Cruz de Tenerife", lat:28.4690, lng:-16.2510, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en Santa Cruz de Tenerife.", events:[]},

  /* === MEDICINAL (clínicas y recursos) === */
  {id:134, name:"Kalapa Clinic", type:"medicinal", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Barcelona", address:"Barcelona (consulta presencial y online)", lat:41.3880, lng:2.1700, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Clínica","Consulta médica"], desc:"Primera clínica de cannabis medicinal de España (2014). Consulta, seguimiento y asesoramiento médico especializado en cannabinoides. No vende cannabis.", events:[]},
  {id:135, name:"Fundación CANNA", type:"medicinal", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Barcelona", address:"Barcelona", lat:41.4030, lng:2.1850, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Investigación","Divulgación"], desc:"Fundación de divulgación científica y análisis sobre cannabis y cannabinoides. Recurso de información, no es un punto de venta.", events:[]},

  /* === MADRID (ampliación) === */
  {id:136, name:"CBD World Madrid", type:"cbd", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Madrid", address:"C. de San Cristóbal 19, 28012 Madrid", lat:40.4140, lng:-3.7060, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Aceites","Cremas"], desc:"Tienda de CBD en el centro de Madrid (Sol/La Latina).", events:[]},
  {id:137, name:"Eurogrow Arganda", type:"grow", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Arganda del Rey", address:"C. Vereda del Guijar 3, 28500 Arganda del Rey, Madrid", lat:40.3010, lng:-3.4380, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop con tienda física en Arganda del Rey.", events:[]},

  /* === CASTILLA Y LEÓN (ampliación) === */
  {id:138, name:"Grow Shop León (Velasquita)", type:"grow", brosin:false, ccaa:"Castilla y León", prov:"León", city:"León", address:"C/ Velasquita 1, 24009 León", lat:42.5950, lng:-5.5700, phone:"987 806 894", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en León.", events:[]},
  {id:139, name:"Grow Shop León (Montemayor)", type:"grow", brosin:false, ccaa:"Castilla y León", prov:"León", city:"León", address:"C/ Jorge Montemayor 36, 24007 León", lat:42.6010, lng:-5.5500, phone:"987 220 063", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en León.", events:[]},
  {id:140, name:"Grow Shop Palencia", type:"grow", brosin:false, ccaa:"Castilla y León", prov:"Palencia", city:"Palencia", address:"C/ Estrada 7, 34002 Palencia", lat:42.0100, lng:-4.5280, phone:"979 101 358", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Palencia.", events:[]},
  {id:141, name:"CBD Zamora (Eduardo Barrón)", type:"cbd", brosin:false, ccaa:"Castilla y León", prov:"Zamora", city:"Zamora", address:"Parque Eduardo Barrón 1, 49018 Zamora", lat:41.5040, lng:-5.7440, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en Zamora.", events:[]},
  {id:142, name:"CBD Zamora (Cuartel Viejo)", type:"cbd", brosin:false, ccaa:"Castilla y León", prov:"Zamora", city:"Zamora", address:"Pl. Cuartel Viejo 7, bajo 3, 49006 Zamora", lat:41.5060, lng:-5.7430, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en el centro de Zamora.", events:[]},

  /* === CASTILLA-LA MANCHA (ampliación) === */
  {id:143, name:"Grow Shop Paradise", type:"grow", brosin:false, ccaa:"Castilla-La Mancha", prov:"Ciudad Real", city:"Ciudad Real", address:"C. Rey 8, 13001 Ciudad Real", lat:38.9860, lng:-3.9270, phone:"", hours:"Lun-Vie 10:00–14:00 y 17:00–20:30, Sáb 10:00–14:00", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Ciudad Real.", events:[]},
  {id:144, name:"Jardín del Cannabis", type:"grow", brosin:false, ccaa:"Castilla-La Mancha", prov:"Guadalajara", city:"Guadalajara", address:"C. Francisco Aritio 156, Pol. Nudo Oeste, nave 19, Guadalajara", lat:40.6320, lng:-3.1900, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Guadalajara.", events:[]},
  {id:145, name:"CBD Azuqueca", type:"cbd", brosin:false, ccaa:"Castilla-La Mancha", prov:"Guadalajara", city:"Azuqueca de Henares", address:"C. Molina de Aragón 2, Local 1, 19200 Azuqueca de Henares, Guadalajara", lat:40.5640, lng:-3.2680, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en Azuqueca de Henares.", events:[]},
  {id:146, name:"Tienda CBD Guadalajara", type:"cbd", brosin:false, ccaa:"Castilla-La Mancha", prov:"Guadalajara", city:"Guadalajara", address:"C. Zaragoza 8, 19005 Guadalajara", lat:40.6300, lng:-3.1620, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en Guadalajara.", events:[]},

  /* === GALICIA (ampliación) === */
  {id:147, name:"Viva María Santiago", type:"grow", brosin:false, ccaa:"Galicia", prov:"A Coruña", city:"Santiago de Compostela", address:"Rúa Rosalía de Castro 116, Santiago de Compostela, A Coruña", lat:42.8770, lng:-8.5500, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Santiago de Compostela.", events:[]},
  {id:148, name:"CBweed Santiago", type:"cbd", brosin:false, ccaa:"Galicia", prov:"A Coruña", city:"Santiago de Compostela", address:"C/ San Pedro de Mezonzo 19, 15701 Santiago de Compostela", lat:42.8780, lng:-8.5380, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en Santiago de Compostela.", events:[]},
  {id:149, name:"Tienda CBD Santiago (Caldeirería)", type:"cbd", brosin:false, ccaa:"Galicia", prov:"A Coruña", city:"Santiago de Compostela", address:"R. da Caldeirería 44, 15703 Santiago de Compostela", lat:42.8790, lng:-8.5440, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en el casco de Santiago.", events:[]},
  {id:150, name:"CBweed Ferrol", type:"cbd", brosin:false, ccaa:"Galicia", prov:"A Coruña", city:"Ferrol", address:"Rúa Real 148 Bajo, 15402 Ferrol, A Coruña", lat:43.4840, lng:-8.2330, phone:"626 948 820", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en Ferrol.", events:[]},

  /* === CÁDIZ / GRANADA (ampliación) === */
  {id:151, name:"Grow/CBD Jerez (Porvera)", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Cádiz", city:"Jerez de la Frontera", address:"C. Porvera 27, 11403 Jerez de la Frontera, Cádiz", lat:36.6870, lng:-6.1320, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD en el centro de Jerez.", events:[]},
  {id:152, name:"CBD Jerez (Larga)", type:"cbd", brosin:false, ccaa:"Andalucía", prov:"Cádiz", city:"Jerez de la Frontera", address:"C. Larga 20, 11402 Jerez de la Frontera, Cádiz", lat:36.6820, lng:-6.1360, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en la calle Larga, Jerez.", events:[]},
  {id:153, name:"Grow Shop Granada (Capolino)", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Granada", city:"Granada", address:"C. Pintor Joaquín Capolino 8, 18013 Granada", lat:37.2010, lng:-3.6080, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Granada.", events:[]},

  /* === ARAGÓN / EXTREMADURA (ampliación) === */
  {id:154, name:"Cherokee Grow Huesca", type:"grow", brosin:false, ccaa:"Aragón", prov:"Huesca", city:"Huesca", address:"C. Valentín Carderera 3, 22003 Huesca", lat:42.1370, lng:-0.4080, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Huesca.", events:[]},
  {id:155, name:"Cannabis Shop Huesca", type:"grow", brosin:false, ccaa:"Aragón", prov:"Huesca", city:"Huesca", address:"C/ Amistad 1, Huesca", lat:42.1320, lng:-0.4090, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD en Huesca.", events:[]},
  {id:156, name:"Cultivo Arte (Mérida)", type:"grow", brosin:false, ccaa:"Extremadura", prov:"Badajoz", city:"Mérida", address:"C/ Medea 8, Las Abadías, Mérida, Badajoz", lat:38.9300, lng:-6.3500, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Mérida.", events:[]},
  {id:157, name:"Mater-Terra (Mérida)", type:"grow", brosin:false, ccaa:"Extremadura", prov:"Badajoz", city:"Mérida", address:"Avda. de los Milagros 38, local 2, 06800 Mérida, Badajoz", lat:38.9150, lng:-6.3450, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD en Mérida.", events:[]},

  /* === CATALUÑA (área metropolitana) === */
  {id:158, name:"Bitox Sabadell", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Sabadell", address:"Pg. de Rubió i Ors 88-90, 08204 Sabadell, Barcelona", lat:41.5480, lng:2.1050, phone:"937 10 48 12", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Sabadell.", events:[]},
  {id:159, name:"La Gla (Terrassa)", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Terrassa", address:"C/ Salmerón 66, 08222 Terrassa, Barcelona", lat:41.5620, lng:2.0180, phone:"937 31 47 51", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Terrassa.", events:[]},
  {id:160, name:"Grow City (Terrassa)", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Terrassa", address:"Av. de Font i Sagué 7, 08227 Terrassa, Barcelona", lat:41.5560, lng:2.0350, phone:"937 86 95 18", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Terrassa.", events:[]},
  {id:161, name:"Grow Terrassa", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Terrassa", address:"Carrer de Carrasco i Formiguera 16, 08224 Terrassa, Barcelona", lat:41.5670, lng:2.0100, phone:"931 68 17 84", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Terrassa.", events:[]},
  {id:162, name:"Grow Shop Badalona (Sant Bru)", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Badalona", address:"Carrer de Sant Bru 127, 08911 Badalona, Barcelona", lat:41.4480, lng:2.2450, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Badalona.", events:[]},
  {id:163, name:"Grow Shop Badalona (Vallmajor)", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Badalona", address:"Carrer del Torrent Vallmajor 74, 08915 Badalona, Barcelona", lat:41.4550, lng:2.2400, phone:"931 81 67 80", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Badalona.", events:[]},

  /* === MÁLAGA (Marbella / Estepona) === */
  {id:164, name:"Costa del Grow (Marbella)", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Málaga", city:"Marbella", address:"C. Juan de la Cosa 2, 29603 Marbella, Málaga", lat:36.5100, lng:-4.8880, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop especializado en Marbella.", events:[]},
  {id:165, name:"Grow Shop Marbella (La Ermita)", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Málaga", city:"Marbella", address:"C/ Diamante, Pol. La Ermita 4, 29603 Marbella, Málaga", lat:36.5120, lng:-4.8820, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Marbella.", events:[]},
  {id:166, name:"Grow/CBD Estepona (J. Martín Méndez)", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Málaga", city:"Estepona", address:"Av. José Martín Méndez 63, 29680 Estepona, Málaga", lat:36.4270, lng:-5.1470, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD en Estepona.", events:[]},
  {id:167, name:"Grow Shop Estepona (San Roque)", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Málaga", city:"Estepona", address:"C. San Roque 44, 29680 Estepona, Málaga", lat:36.4260, lng:-5.1450, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Estepona.", events:[]},

  /* === ALICANTE (Torrevieja / Benidorm) === */
  {id:168, name:"FlorProhibida Torrevieja", type:"grow", brosin:false, ccaa:"C. Valenciana", prov:"Alicante", city:"Torrevieja", address:"Calle María Parodi 41, 03181 Torrevieja, Alicante", lat:37.9780, lng:-0.6820, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD en Torrevieja.", events:[]},
  {id:169, name:"Cultivador Dorado CBD Grow", type:"cbd", brosin:false, ccaa:"C. Valenciana", prov:"Alicante", city:"Torrevieja", address:"Caballero de Rodas 20, 03181 Torrevieja, Alicante", lat:37.9800, lng:-0.6810, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Cultivo"], desc:"CBD y grow shop en Torrevieja.", events:[]},
  {id:170, name:"Benidorm Grow Shop (Supernatural)", type:"grow", brosin:false, ccaa:"C. Valenciana", prov:"Alicante", city:"Benidorm", address:"C/ Maravall 8, local Supernatural, 03501 Benidorm, Alicante", lat:38.5380, lng:-0.1310, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Benidorm desde 2008.", events:[]},

  /* === MEDICINAL (ampliación — Madrid) === */
  {id:171, name:"MEDCAN", type:"medicinal", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Madrid", address:"Madrid (centro de información y consulta médica)", lat:40.4200, lng:-3.7000, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Consulta médica","Información"], desc:"Centro de información y consulta médica sobre el uso terapéutico del cannabis, con productos derivados del cáñamo. No es un dispensario.", events:[]},
  {id:172, name:"Dos Emociones", type:"medicinal", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Madrid", address:"Madrid (asociación de pacientes)", lat:40.4100, lng:-3.7050, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Asociación","Pacientes"], desc:"Primera asociación de pacientes de cannabis terapéutico de España (2014). Acompañamiento e información a pacientes. Impulsora del Observatorio Español del Cannabis Medicinal.", events:[]},
  {id:173, name:"Asociación Amala", type:"medicinal", brosin:false, ccaa:"Región de Murcia", prov:"Murcia", city:"Murcia", address:"C. Mahón 12, 30001 Murcia", lat:37.9840, lng:-1.1280, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Asociación","Consulta médica"], desc:"Asociación terapéutica sin ánimo de lucro: apoyo a pacientes y consulta médica online (con MEDCAN).", events:[]},

  /* === MADRID metropolitano === */
  {id:174, name:"Greenery 420 CBD Alcalá", type:"cbd", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Alcalá de Henares", address:"Calle Mayor 28, Alcalá de Henares, Madrid", lat:40.4820, lng:-3.3650, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Flores","Aceites"], desc:"Tienda de CBD en Alcalá de Henares.", events:[]},
  {id:175, name:"Boutique del Cannabis Medicinal", type:"grow", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Alcalá de Henares", address:"Avenida Guadalajara 16, Alcalá de Henares, Madrid", lat:40.4840, lng:-3.3600, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD en Alcalá de Henares.", events:[]},
  {id:176, name:"Grow Shop Fuenlabrada", type:"grow", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Fuenlabrada", address:"C. Canarias 16, 28945 Fuenlabrada, Madrid", lat:40.2840, lng:-3.7940, phone:"916 973 464", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Fuenlabrada.", events:[]},
  {id:177, name:"Urban Grow Leganés", type:"grow", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Leganés", address:"Leganés, Madrid (dirección por confirmar)", lat:40.3280, lng:-3.7630, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Leganés.", events:[]},

  /* === CATALUÑA metropolitana === */
  {id:178, name:"Grow/CBD Mataró", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Mataró", address:"Carrer de la Repuntadora 2, Local 3, 08302 Mataró, Barcelona", lat:41.5350, lng:2.4450, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD en Mataró.", events:[]},
  {id:179, name:"Grow Shop Hospitalet", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"L'Hospitalet de Llobregat", address:"Av. Carrilet 327, bajos, 08907 L'Hospitalet de Llobregat, Barcelona", lat:41.3600, lng:2.1000, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en L'Hospitalet de Llobregat.", events:[]},
  {id:180, name:"La Grow Manresa", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Manresa", address:"Carrer Caritat 7, bajo, 08241 Manresa, Barcelona", lat:41.7280, lng:1.8270, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop con +12 años en Manresa.", events:[]},

  /* === MURCIA === */
  {id:181, name:"Grow Shop Plantiagro", type:"grow", brosin:false, ccaa:"Región de Murcia", prov:"Murcia", city:"Puerto Lumbreras", address:"Camino Viejo de Lorca 110, 30890 Puerto Lumbreras, Murcia", lat:37.5650, lng:-1.8100, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Puerto Lumbreras (Lorca).", events:[]},

  /* === ALMERÍA (litoral) === */
  {id:182, name:"Grow Shop Oro Verde", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Almería", city:"Roquetas de Mar", address:"Av. Pablo Picasso 75, 04740 Roquetas de Mar, Almería", lat:36.7640, lng:-2.6150, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","Semillas"], desc:"Grow shop en Roquetas de Mar.", events:[]},
  {id:183, name:"Houseplant Roquetas", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Almería", city:"Roquetas de Mar", address:"Avda. Sabinal 242, Roquetas de Mar, Almería", lat:36.7660, lng:-2.6180, phone:"950 931 148", hours:"Lun-Vie 10:00–14:00 y 17:00–21:00, Sáb 11:00–13:00 y 17:30–21:00", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Roquetas de Mar.", events:[]},
  {id:184, name:"Grow Shop Garrucha (CANNA)", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Almería", city:"Garrucha", address:"Ctra. de Vera-Garrucha, Local 9 (Urb. Solana del Mar), 04630 Garrucha, Almería", lat:37.1830, lng:-1.8200, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Garrucha (Almería).", events:[]},

  /* === EMPRESAS (bancos de semillas, distribuidoras, proveedores de CSC) === */
  {id:185, name:"Sweet Seeds", type:"empresa", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"València", address:"C/ Reverendo José Mª Pinazo 9, 46020 València", lat:39.4870, lng:-0.3580, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Banco de semillas"], desc:"Banco español de semillas de cannabis feminizadas, con sede en Valencia. +10 años de genética propia.", events:[]},
  {id:186, name:"Dinafem Seeds", type:"empresa", brosin:false, ccaa:"País Vasco", prov:"Gipuzkoa", city:"Donostia-San Sebastián", address:"Calle Aldamar 32, 20003 Donostia-San Sebastián", lat:43.3230, lng:-1.9850, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Banco de semillas"], desc:"Banco de semillas español (2005), uno de los referentes a nivel europeo.", events:[]},
  {id:187, name:"Kannabia Seeds", type:"empresa", brosin:false, ccaa:"Andalucía", prov:"Granada", city:"Granada", address:"Granada (banco de semillas)", lat:37.1770, lng:-3.5980, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Banco de semillas"], desc:"Banco de semillas con sede en Granada, +61 variedades y distribución en 20 países.", events:[]},
  {id:188, name:"Multi-i Distribución", type:"empresa", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Barcelona", address:"Barcelona (mayorista · sede por confirmar)", lat:41.3900, lng:2.1600, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Mayorista","Papel","Parafernalia"], desc:"Distribuidora mayorista de CBD, papel de liar y parafernalia para grow shops y estancos.", events:[]},
  {id:189, name:"SmokApp", type:"empresa", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"España", address:"España (software para clubes · consulta smokapp.com)", lat:40.4168, lng:-3.7038, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Software CSC","Proveedor"], desc:"Software de gestión para clubes sociales de cannabis (socios, dispensación, comunicación).", events:[]},

  /* === MEDICINAL (ampliación — Valencia y Madrid) === */
  {id:190, name:"Asociación La Flora", type:"medicinal", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"València", address:"València (asociación de investigación cannábica)", lat:39.4700, lng:-0.3760, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Asociación","Consulta médica"], desc:"Asociación de investigación cannábica con asesoramiento médico sobre cannabis terapéutico desde 2012.", events:[]},
  {id:191, name:"Observatorio Español del Cannabis Medicinal", type:"medicinal", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Madrid", address:"España (observatorio · oedcm.com)", lat:40.4168, lng:-3.7000, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Observatorio","Información"], desc:"Observatorio formado por investigadores, médicos y asociaciones de pacientes de cannabis medicinal. Recurso de información y referencia.", events:[]},

  /* === EMPRESAS · Bancos de semillas españoles === */
  {id:192, name:"Delicious Seeds", type:"empresa", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"València", address:"València (banco de semillas)", lat:39.4700, lng:-0.3760, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Banco de semillas"], desc:"Banco de semillas (2009), conocido por Sugar Black Rose y Caramelo, con línea medicinal.", events:[]},
  {id:193, name:"Eva Seeds", type:"empresa", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"L'Hospitalet de Llobregat", address:"Travessera de les Corts 48, L'Hospitalet de Llobregat, Barcelona", lat:41.3620, lng:2.1000, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Banco de semillas"], desc:"Banco de feminizadas orgánicas creado por La Huerta Grow Shop.", events:[]},
  {id:194, name:"Pyramid Seeds", type:"empresa", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Barcelona", address:"Barcelona (banco de semillas)", lat:41.3900, lng:2.1700, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Banco de semillas"], desc:"Banco con +20 años, conocido por Tutankhamon.", events:[]},
  {id:195, name:"Genehtik Seeds", type:"empresa", brosin:false, ccaa:"País Vasco", prov:"Bizkaia", city:"Bilbao", address:"Bilbao (banco de semillas)", lat:43.2630, lng:-2.9350, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Banco de semillas"], desc:"Banco vasco, origen de la Kritikal Bilbo. Muy premiado.", events:[]},
  {id:196, name:"Ripper Seeds", type:"empresa", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Barcelona", address:"Barcelona (banco de semillas)", lat:41.3950, lng:2.1600, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Banco de semillas"], desc:"Banco (2011), genética de élite como Zombie Kush.", events:[]},
  {id:197, name:"Medical Seeds", type:"empresa", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Barcelona", address:"Barcelona (banco de semillas)", lat:41.3880, lng:2.1650, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Banco de semillas"], desc:"Banco (2008) orientado a uso medicinal, adaptado al clima español.", events:[]},
  {id:198, name:"BSF Seeds", type:"empresa", brosin:false, ccaa:"Asturias", prov:"Asturias", city:"Cangas del Narcea", address:"Calle La Fuente 27, Cangas del Narcea, Asturias", lat:43.1770, lng:-6.5480, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Banco de semillas"], desc:"Banco (2017) especializado en genéticas norteamericanas.", events:[]},
  {id:199, name:"Blimburn Seeds", type:"empresa", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Mataró", address:"Ronda President Irla 28, Mataró, Barcelona", lat:41.5400, lng:2.4450, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Banco de semillas"], desc:"Amplio catálogo de feminizadas, autos y CBD.", events:[]},
  {id:200, name:"Elite Seeds", type:"empresa", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"Paterna", address:"Parc Científic de la Universitat de València, Paterna", lat:39.5090, lng:-0.4180, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Banco de semillas","CBD"], desc:"Banco (2007) especializado en CBD y cannabinoides raros (THCV, CBDV).", events:[]},
  {id:201, name:"Cannabiogen", type:"empresa", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"València", address:"València (banco de semillas)", lat:39.4680, lng:-0.3770, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Banco de semillas"], desc:"Banco pionero (+30 años) especializado en landraces.", events:[]},
  {id:202, name:"ACE Seeds", type:"empresa", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"Rocafort", address:"Apdo. 31, 46111 Rocafort, Valencia", lat:39.5280, lng:-0.3760, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Banco de semillas"], desc:"Banco de variedades landrace y sativas puras.", events:[]},
  {id:203, name:"Seedstockers", type:"empresa", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Barcelona", address:"Barcelona (banco de semillas)", lat:41.3870, lng:2.1690, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Banco de semillas"], desc:"Banco (2017), genética de calidad a precio asequible.", events:[]},
  {id:204, name:"R-Kiem Seeds", type:"empresa", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Barcelona", address:"Barcelona (banco de semillas)", lat:41.3910, lng:2.1730, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Banco de semillas"], desc:"Cooperativa (1998), preservación de genéticas orgánicas.", events:[]},
  {id:205, name:"Buddha Seeds", type:"empresa", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"València", address:"València (banco de semillas)", lat:39.4720, lng:-0.3800, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Banco de semillas"], desc:"Banco (2005), referente en autoflorecientes (Magnum, Deimos).", events:[]},

  /* === EMPRESAS · Distribuidoras, laboratorios y packaging === */
  {id:206, name:"Ilitek", type:"empresa", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Igualada", address:"Avenida Europa 27, 08700 Igualada, Barcelona", lat:41.5810, lng:1.6170, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Mayorista","Cultivo"], desc:"Fabricante y distribuidor mayorista de equipos de cultivo indoor y accesorios.", events:[]},
  {id:207, name:"Algarix Partners", type:"empresa", brosin:false, ccaa:"C. Valenciana", prov:"Alicante", city:"Elche", address:"Partida Algoros 104-I, Ctra. del León km 0,6, 03293 Elche", lat:38.2400, lng:-0.7100, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Mayorista","Papel","Parafernalia"], desc:"Mayorista de papel, parafernalia y accesorios (almacén de 1.500 m²).", events:[]},
  {id:208, name:"LaMota Distribución", type:"empresa", brosin:false, ccaa:"País Vasco", prov:"Gipuzkoa", city:"Donostia-San Sebastián", address:"C/ Aldamar 28, Donostia-San Sebastián", lat:43.3230, lng:-1.9850, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Mayorista","Cultivo"], desc:"Distribuidor grow shop con +4.500 productos.", events:[]},
  {id:209, name:"Green Time Distribuciones", type:"empresa", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"Xàtiva", address:"Xàtiva (distribuidora)", lat:38.9870, lng:-0.5180, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Mayorista","Cultivo"], desc:"Distribuidora a España y Europa desde 2012.", events:[]},
  {id:210, name:"Cannactiva", type:"empresa", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Barcelona", address:"Plaça d'Osca 6, 08014 Barcelona", lat:41.3760, lng:2.1450, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Mayorista"], desc:"Marca nº1 de CBD en España, con distribución mayorista B2B.", events:[]},
  {id:211, name:"Canna CBD Distribution", type:"empresa", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Barcelona", address:"Barcelona (mayorista CBD)", lat:41.3900, lng:2.1500, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["CBD","Mayorista"], desc:"Mayorista de CBD legal para toda Europa.", events:[]},
  {id:212, name:"Allora Labs", type:"empresa", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Viladecans", address:"Parc Agròpolis UPC, Viladecans, Barcelona", lat:41.3050, lng:2.0450, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Laboratorio","Análisis"], desc:"Laboratorio de análisis de cannabinoides, terpenos, metales y pesticidas. Trabaja con Energy Control.", events:[]},
  {id:213, name:"AGQ Labs", type:"empresa", brosin:false, ccaa:"Andalucía", prov:"Sevilla", city:"Burguillos", address:"Ctra. A-8013 km 20,8, 41220 Burguillos, Sevilla", lat:37.5850, lng:-5.9660, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Laboratorio","Análisis"], desc:"Centro tecnológico con análisis de cáñamo y seguimiento nutricional.", events:[]},
  {id:214, name:"THContainers", type:"empresa", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Granollers", address:"Avinguda Sant Julià 125, 08403 Granollers, Barcelona", lat:41.6080, lng:2.2870, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Packaging","Envases"], desc:"Packaging personalizable para cannabis, CBD y asociaciones.", events:[]},
  {id:215, name:"Cheeba Distribuciones", type:"empresa", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"València", address:"València (distribuidor mayorista)", lat:39.4650, lng:-0.3750, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Mayorista","Parafernalia"], desc:"Distribuidor mayorista de parafernalia y cultivo (+10 años).", events:[]},

  /* === EMPRESAS · Software CSC y asesorías legales === */
  {id:216, name:"Cannabis Club Systems", type:"empresa", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Madrid", address:"Madrid (software CSC)", lat:40.4200, lng:-3.7020, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Software CSC","Proveedor"], desc:"Software de operativa de clubes desde 2014, +900 clientes en varios países.", events:[]},
  {id:217, name:"Gestión Verde (Software Cannabis)", type:"empresa", brosin:false, ccaa:"Cataluña", prov:"Tarragona", city:"Vila-seca", address:"Vila-seca, Tarragona (software CSC)", lat:41.1110, lng:1.1440, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Software CSC","Proveedor"], desc:"Software cloud de gestión de clubes (socios, stock, genéticas, RGPD).", events:[]},
  {id:218, name:"B2Weed", type:"empresa", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Barcelona", address:"Barcelona (software / ERP)", lat:41.3880, lng:2.1700, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Software CSC","ERP"], desc:"ERP para clubes, tiendas CBD y grow shops (multi-local, stock en tiempo real).", events:[]},
  {id:219, name:"Brotsanbert (asesoría legal)", type:"empresa", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"València", address:"Alcalde Domingo Torres 4, 46020 València", lat:39.4760, lng:-0.3510, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Asesoría legal","Cannabis"], desc:"Bufete +18 años especializado en cannabis: asesora a ~70 asociaciones y 200 empresas.", events:[]},
  {id:220, name:"THC Abogados", type:"empresa", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Madrid", address:"C. del Laurel 21, 1º B, 28005 Madrid", lat:40.4020, lng:-3.7080, phone:"915 482 699", hours:"", verified:false, rating:0, reviews:0, tags:["Asesoría legal","Cannabis"], desc:"Especialistas en penal y administrativo para CSC, grow shops, CBD y bancos de semillas.", events:[]},
  {id:221, name:"Sofer Abogados", type:"empresa", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Madrid", address:"C/ General Ricardos 127, 28019 Madrid", lat:40.3920, lng:-3.7250, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Asesoría legal","CBD"], desc:"Despacho centrado en CBD y cannabis, con red internacional.", events:[]},
  {id:222, name:"E-Parafernalia", type:"empresa", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Madrid", address:"Madrid (head shop desde 2002)", lat:40.4160, lng:-3.7030, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Parafernalia","Vaporizadores"], desc:"Head shop: vaporizadores, grinders, semillas y accesorios.", events:[]},

  /* === MEDICINAL (ampliación multi-región) === */
  {id:223, name:"Cannabity Healthcare", type:"medicinal", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Sant Cugat del Vallès", address:"Sant Cugat del Vallès, Barcelona (teleconsulta)", lat:41.4720, lng:2.0860, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Teleconsulta","Certificado"], desc:"Teleconsulta médica de cannabis terapéutico con certificado de uso; laboratorio propio.", events:[]},
  {id:224, name:"SEIC (Sociedad Española de Investigación sobre Cannabinoides)", type:"medicinal", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Madrid", address:"Fac. de Medicina, Univ. Complutense, Madrid", lat:40.4400, lng:-3.7280, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Investigación","Ciencia"], desc:"Sociedad científica de investigadores sobre cannabinoides.", events:[]},
  {id:225, name:"ICEERS", type:"medicinal", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Barcelona", address:"C/ Sepúlveda 65, of. 2, 08015 Barcelona", lat:41.3810, lng:2.1590, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Investigación","Pacientes"], desc:"Fundación de ciencia, política y educación sobre cannabis (proyecto Cannabmed).", events:[]},
  {id:226, name:"Unidad del Dolor · Hospital Nacional de Parapléjicos", type:"medicinal", brosin:false, ccaa:"Castilla-La Mancha", prov:"Toledo", city:"Toledo", address:"Hospital Nacional de Parapléjicos, Toledo", lat:39.8790, lng:-4.0300, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Hospital","Dolor"], desc:"Unidad del Dolor que trata dolor neuropático y espasticidad (prescripción de Sativex bajo criterios).", events:[]},
  {id:227, name:"Medican Map", type:"medicinal", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Consulta online", address:"Consulta online (nacional)", lat:40.4168, lng:-3.7000, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Teleconsulta","Certificado"], desc:"Plataforma sanitaria que conecta médicos colegiados con usuarios; certificados de uso terapéutico.", events:[]},
  {id:228, name:"Dr. Javier Pedraza", type:"medicinal", brosin:false, ccaa:"Extremadura", prov:"Cáceres", city:"Consulta online", address:"Consulta médica online (Extremadura)", lat:39.4700, lng:-6.3700, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Consulta médica","Online"], desc:"Médico de familia y consultor en tratamientos con cannabis (miembro de SEIC y OECM).", events:[]},

  /* === GROW / CBD · ciudades medianas y pequeñas === */
  {id:229, name:"A Growta", type:"grow", brosin:false, ccaa:"Galicia", prov:"Lugo", city:"Lugo", address:"Rúa Saúde 25 Baixo, 27004 Lugo", lat:43.0100, lng:-7.5560, phone:"982 809 558", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Lugo.", events:[]},
  {id:230, name:"Ketama Grow Shop", type:"grow", brosin:false, ccaa:"Galicia", prov:"A Coruña", city:"Ferrol", address:"Calle República Argentina 29, 15404 Ferrol", lat:43.4840, lng:-8.2320, phone:"656 675 297", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Ferrol.", events:[]},
  {id:231, name:"Ganya Growshop", type:"grow", brosin:false, ccaa:"Galicia", prov:"A Coruña", city:"Ferrol", address:"Calle Carlos III 30, 15403 Ferrol", lat:43.4870, lng:-8.2360, phone:"981 948 988", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Ferrol.", events:[]},
  {id:232, name:"O Dispensario", type:"cbd", brosin:false, ccaa:"Galicia", prov:"Ourense", city:"Ourense", address:"Rúa da Paz 14, 32005 Ourense", lat:42.3370, lng:-7.8640, phone:"988 231 489", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en Ourense.", events:[]},
  {id:233, name:"Florprohibida Cuenca", type:"grow", brosin:false, ccaa:"Castilla-La Mancha", prov:"Cuenca", city:"Cuenca", address:"C/ Dalmacio García Izcara 7, 16004 Cuenca", lat:40.0700, lng:-2.1370, phone:"969 692 050", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Cuenca.", events:[]},
  {id:234, name:"LOLA420 Growshop", type:"grow", brosin:false, ccaa:"Castilla y León", prov:"Segovia", city:"Segovia", address:"C/ Juan Bravo 48, 40001 Segovia", lat:40.9480, lng:-4.1180, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Segovia.", events:[]},
  {id:235, name:"All 2 Grow Shop", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Girona", city:"Girona", address:"Carrer de Sardenya 6 bajos, 17007 Girona", lat:41.9790, lng:2.8210, phone:"972 487 921", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Girona.", events:[]},
  {id:236, name:"La Meca Grow & CBD", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Tarragona", city:"Tarragona", address:"Carrer dels Caputxins 18-A bajo 2, 43001 Tarragona", lat:41.1180, lng:1.2500, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD en Tarragona.", events:[]},
  {id:237, name:"Green Wolf Grow Shop", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Tarragona", city:"Reus", address:"Carrer de Vilallonga 15 bajos 5, 43204 Reus", lat:41.1560, lng:1.1070, phone:"977 316 801", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Reus.", events:[]},
  {id:238, name:"La Bella Grow Shop", type:"grow", brosin:false, ccaa:"Cataluña", prov:"Tarragona", city:"Reus", address:"Plaça Almoster 1 bajos, Reus", lat:41.1600, lng:1.1050, phone:"977 084 359", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Reus.", events:[]},
  {id:239, name:"Houseplant Cáceres", type:"grow", brosin:false, ccaa:"Extremadura", prov:"Cáceres", city:"Cáceres", address:"C/ Santa Apolonia 2, 10002 Cáceres", lat:39.4750, lng:-6.3730, phone:"927 223 337", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Cáceres.", events:[]},
  {id:240, name:"Resina Grow", type:"grow", brosin:false, ccaa:"Extremadura", prov:"Cáceres", city:"Cáceres", address:"C/ Hernando de Soto 12, 10002 Cáceres", lat:39.4740, lng:-6.3720, phone:"927 226 039", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Cáceres.", events:[]},
  {id:241, name:"Ave María Grow Shop", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Cádiz", city:"Algeciras", address:"Calle Emilio Castelar 22, 11201 Algeciras, Cádiz", lat:36.1290, lng:-5.4510, phone:"856 123 988", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Algeciras.", events:[]},
  {id:242, name:"Sativa Grow (Gandía)", type:"grow", brosin:false, ccaa:"C. Valenciana", prov:"Valencia", city:"Gandía", address:"C/ Transport 30, nave 33, 46702 Gandía, Valencia", lat:38.9680, lng:-0.1810, phone:"962 867 608", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Gandía.", events:[]},
  {id:243, name:"Yerbagüena Grow Shop", type:"grow", brosin:false, ccaa:"C. Valenciana", prov:"Alicante", city:"Elda", address:"Calle Francisco Alonso 4, 03600 Elda, Alicante", lat:38.4780, lng:-0.7900, phone:"965 381 976", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Elda.", events:[]},
  {id:244, name:"Alkimia", type:"grow", brosin:false, ccaa:"Castilla-La Mancha", prov:"Toledo", city:"Talavera de la Reina", address:"Pº de la Estación 18, 45600 Talavera de la Reina, Toledo", lat:39.9620, lng:-4.8300, phone:"605 907 926", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Talavera de la Reina.", events:[]},
  {id:245, name:"Hortikultura Grow Shop", type:"grow", brosin:false, ccaa:"Castilla-La Mancha", prov:"Toledo", city:"Talavera de la Reina", address:"Postiguillo 15, 45600 Talavera de la Reina, Toledo", lat:39.9640, lng:-4.8330, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Talavera de la Reina.", events:[]},
  {id:246, name:"Green Plan Grow Shop", type:"grow", brosin:false, ccaa:"Aragón", prov:"Teruel", city:"Teruel", address:"Calle Río Duero 5, 44003 Teruel", lat:40.3450, lng:-1.1070, phone:"978 611 820", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en Teruel.", events:[]},
  {id:247, name:"Eurogrow Ávila", type:"grow", brosin:false, ccaa:"Castilla y León", prov:"Ávila", city:"Ávila", address:"Calle Río Esla 49, 05004 Ávila", lat:40.6560, lng:-4.6810, phone:"", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo","CBD"], desc:"Grow shop y CBD en Ávila.", events:[]},
  {id:248, name:"Bendita María Grow Shop", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Almería", city:"El Ejido", address:"Avenida del Oasis 65, 04700 El Ejido, Almería", lat:36.7760, lng:-2.8140, phone:"950 938 635", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en El Ejido.", events:[]},
  {id:249, name:"Gardenlights", type:"grow", brosin:false, ccaa:"Andalucía", prov:"Almería", city:"El Ejido", address:"Calle País de Gales 4, El Ejido, Almería", lat:36.7780, lng:-2.8100, phone:"950 483 994", hours:"", verified:false, rating:0, reviews:0, tags:["Cultivo"], desc:"Grow shop en El Ejido.", events:[]},
  {id:250, name:"La Tía María CBD (Melilla)", type:"cbd", brosin:false, ccaa:"Melilla", prov:"Melilla", city:"Melilla", address:"Av. Duquesa de la Victoria 8, 52004 Melilla", lat:35.2920, lng:-2.9480, phone:"640 803 179", hours:"", verified:false, rating:0, reviews:0, tags:["CBD"], desc:"Tienda de CBD en Melilla.", events:[]}
];
