/* ===========================================================
   BROSIN · páginas de contenido (Sobre nosotros · Para empresarios)
   Como Saber+: los textos son datos, así que añadir un idioma es
   copiar un bloque. Los que falten caen a inglés, y luego a español.

   NO se traduce el aviso legal, a propósito: un texto legal pasado
   por traducción automática crea dos versiones que no coinciden.
   =========================================================== */
(function (root) {
  'use strict';

  var P = {};

  P.es = {
    nos: { t: "Sobre nosotros",
      lead: "Brosin nació en <b>2018 en Torre del Mar (Málaga)</b>, fundado por dos amigos con un sueño común: crear un club social de fumadores diferente, donde la <b>calidad</b> y la <b>comunidad</b> fueran lo primero.",
      quote: "\"B\" de be, de ser. Rosin, la resina. Bee, la abeja.",
      firma: "Bro, no te quedes sin, Brosin.",
      p1: "De aquel primer local nació una colmena: hoy somos varios espacios <b>«DogRoom by Brosin»</b>, <b>«El Submarino by Brosin»</b> y más, por la Costa del Sol y la Costa Tropical, siempre con el mismo ojo, la misma sonrisa y el mismo buen rollo.",
      h_app: "Qué es esta app",
      p_app: "Brosin es el mapa de referencia para encontrar <b>clubes sociales, grow shops y tiendas de CBD</b> de toda España y Europa, con información veraz y reducción de riesgos. No vendemos cannabis: somos una guía informativa y de comunidad.",
      h_mis: "Misión",
      p_mis: "Que la comunidad cannábica se reúna sin prejuicios, con calidad real, ambiente relajado y la cercanía de un colega — sin importar tu edad, tu estilo de vida o cuánto sepas del mundo del cannabis.",
      h_vis: "Visión",
      p_vis: "Ser la marca de clubes sociales de cannabis más reconocible de España, y el referente en Europa, sin perder nunca la esencia de barrio con la que nació en Torre del Mar.",
      h_val: "Lo que no se negocia",
      vals: [["Calidad sin atajos","El producto, el local y hasta el vaso, cuidados al detalle."],
             ["Natural, como la miel","Hablamos claro, sin artificios ni postureo."],
             ["Atrevida con criterio","Más allá de lo esperado, sin volverse ruido."],
             ["La colmena primero","El socio de 20 y el de 85 comparten mesa y se sienten en casa."]],
      pie: "Brosin promueve el consumo responsable y la reducción de riesgos. Solo +18." },
    emp: { t: "Para empresarios", sub: "Sal en el mapa de referencia",
      lead: "¿Tienes un <b>club social, grow shop o tienda de CBD</b>? Aparece en Brosin y llega a la gente que justo está buscando lo que ofreces. <b>Empezar es gratis.</b>",
      h_por: "Por qué estar en Brosin",
      por: ["<b>Visibilidad gratis</b> ante una comunidad que busca clubes, grows y CBD.",
            "Apareces en el <b>mapa de tu zona</b> y en las búsquedas y filtros por provincia.",
            "Podrás <b>publicar tus novedades y promociones</b> (muy pronto).",
            "Formas parte de una <b>marca con identidad</b> y una comunidad real."],
      h_tar: "Tarifas",
      planes: [
        { n:"Básico", b:"Gratis", precio:"0 €", mes:"", items:["Ficha verificada en el mapa","Datos de contacto y horario","Apareces en búsquedas y filtros"] },
        { n:"Destacado", b:"El más elegido", precio:"39 €", mes:"/ mes", items:["Todo lo del plan Básico","Fotos de tu local","Apareces el primero en tu ciudad","Publica tus novedades y promociones","Estadísticas de cuánta gente te ve"] },
        { n:"Premium", b:"A medida", precio:"A consultar", mes:"", items:["Todo lo del plan Destacado","Posición destacada en tu provincia","Campañas y colaboraciones con Brosin"] }],
      nota: "Tarifas orientativas, sujetas a cambios durante la fase de lanzamiento.",
      cta: "Añade tu local gratis",
      dudas: "¿Dudas? Escríbenos a <b>hola@brosin.app</b>, WhatsApp <b>644 46 61 34</b> o Instagram <b>@brosinculture</b>." }
  };

  P.en = {
    nos: { t: "About us",
      lead: "Brosin was born in <b>2018 in Torre del Mar (Málaga)</b>, founded by two friends with a shared dream: to build a different kind of smokers' social club, one where <b>quality</b> and <b>community</b> came first.",
      quote: "\"B\" for be. Rosin, the resin. Bee, the honeybee.",
      firma: "Bro, no te quedes sin, Brosin.",
      p1: "That first venue grew into a hive: today we're several spaces — <b>«DogRoom by Brosin»</b>, <b>«El Submarino by Brosin»</b> and more — across the Costa del Sol and the Costa Tropical, always with the same eye, the same smile and the same good vibes.",
      h_app: "What this app is",
      p_app: "Brosin is the reference map for finding <b>social clubs, grow shops and CBD stores</b> across Spain and Europe, with honest information and harm reduction. We don't sell cannabis: we're an information and community guide.",
      h_mis: "Mission",
      p_mis: "For the cannabis community to gather without prejudice, with real quality, a relaxed atmosphere and the warmth of a mate — whatever your age, your lifestyle or how much you know about cannabis.",
      h_vis: "Vision",
      p_vis: "To be the most recognisable cannabis social club brand in Spain, and the benchmark in Europe, without ever losing the neighbourhood soul it was born with in Torre del Mar.",
      h_val: "What we don't compromise on",
      vals: [["Quality, no shortcuts","The product, the venue, right down to the glass — looked after in detail."],
             ["Natural, like honey","We speak plainly, no frills, no posturing."],
             ["Bold, but with judgement","Beyond the expected, without becoming noise."],
             ["The hive first","The 20-year-old member and the 85-year-old share a table and both feel at home."]],
      pie: "Brosin promotes responsible use and harm reduction. 18+ only." },
    emp: { t: "For business owners", sub: "Get on the reference map",
      lead: "Do you run a <b>social club, grow shop or CBD store</b>? Get listed on Brosin and reach the people already looking for what you offer. <b>Getting started is free.</b>",
      h_por: "Why be on Brosin",
      por: ["<b>Free visibility</b> to a community actively looking for clubs, grow shops and CBD.",
            "You appear on the <b>map of your area</b> and in searches and province filters.",
            "You'll be able to <b>post your news and promotions</b> (coming soon).",
            "You're part of a <b>brand with identity</b> and a real community."],
      h_tar: "Pricing",
      planes: [
        { n:"Basic", b:"Free", precio:"€0", mes:"", items:["Verified listing on the map","Contact details and opening hours","You show up in searches and filters"] },
        { n:"Featured", b:"Most chosen", precio:"€39", mes:"/ month", items:["Everything in Basic","Photos of your venue","You appear first in your city","Post your news and promotions","Stats on how many people see you"] },
        { n:"Premium", b:"Tailored", precio:"On request", mes:"", items:["Everything in Featured","Top placement in your province","Campaigns and collaborations with Brosin"] }],
      nota: "Indicative pricing, subject to change during the launch phase.",
      cta: "Add your place, free",
      dudas: "Questions? Write to <b>hola@brosin.app</b>, WhatsApp <b>+34 644 46 61 34</b> or Instagram <b>@brosinculture</b>." }
  };

  P.de = {
    nos: { t: "Über uns",
      lead: "Brosin entstand <b>2018 in Torre del Mar (Málaga)</b>, gegründet von zwei Freunden mit einem gemeinsamen Traum: einen anderen Social Club für Raucher zu schaffen, in dem <b>Qualität</b> und <b>Gemeinschaft</b> an erster Stelle stehen.",
      quote: "\"B\" wie be, wie sein. Rosin, das Harz. Bee, die Biene.",
      firma: "Bro, no te quedes sin, Brosin.",
      p1: "Aus dem ersten Laden wurde ein Bienenstock: heute sind wir mehrere Orte — <b>«DogRoom by Brosin»</b>, <b>«El Submarino by Brosin»</b> und weitere — an der Costa del Sol und der Costa Tropical, immer mit demselben Blick, demselben Lächeln und derselben guten Stimmung.",
      h_app: "Was diese App ist",
      p_app: "Brosin ist die Referenzkarte, um <b>Social Clubs, Grow Shops und CBD-Läden</b> in ganz Spanien und Europa zu finden — mit ehrlichen Informationen und Risikominimierung. Wir verkaufen kein Cannabis: wir sind ein Informations- und Community-Guide.",
      h_mis: "Mission",
      p_mis: "Dass sich die Cannabis-Community ohne Vorurteile trifft, mit echter Qualität, entspannter Atmosphäre und der Nähe eines Kumpels — egal wie alt du bist, wie du lebst oder wie viel du über Cannabis weißt.",
      h_vis: "Vision",
      p_vis: "Die bekannteste Marke für Cannabis-Social-Clubs in Spanien zu sein und der Maßstab in Europa — ohne je die Kiez-Seele zu verlieren, mit der alles in Torre del Mar begann.",
      h_val: "Worüber wir nicht verhandeln",
      vals: [["Qualität ohne Abkürzungen","Das Produkt, der Laden, bis hin zum Glas — mit Liebe zum Detail."],
             ["Natürlich, wie Honig","Wir reden Klartext, ohne Schnickschnack und Angeberei."],
             ["Mutig, aber mit Verstand","Über das Erwartbare hinaus, ohne zum Lärm zu werden."],
             ["Der Bienenstock zuerst","Das Mitglied mit 20 und das mit 85 sitzen am selben Tisch und fühlen sich zu Hause."]],
      pie: "Brosin steht für verantwortungsvollen Konsum und Risikominimierung. Nur ab 18." },
    emp: { t: "Für Unternehmen", sub: "Komm auf die Referenzkarte",
      lead: "Hast du einen <b>Social Club, Grow Shop oder CBD-Laden</b>? Lass dich bei Brosin eintragen und erreiche genau die Leute, die danach suchen. <b>Der Einstieg ist kostenlos.</b>",
      h_por: "Warum auf Brosin",
      por: ["<b>Kostenlose Sichtbarkeit</b> bei einer Community, die gezielt nach Clubs, Grow Shops und CBD sucht.",
            "Du erscheinst auf der <b>Karte deiner Gegend</b> sowie in Suche und Provinzfiltern.",
            "Du kannst bald <b>Neuigkeiten und Aktionen veröffentlichen</b> (demnächst).",
            "Du bist Teil einer <b>Marke mit Haltung</b> und einer echten Community."],
      h_tar: "Preise",
      planes: [
        { n:"Basis", b:"Kostenlos", precio:"0 €", mes:"", items:["Verifizierter Eintrag auf der Karte","Kontaktdaten und Öffnungszeiten","Du erscheinst in Suche und Filtern"] },
        { n:"Hervorgehoben", b:"Am beliebtesten", precio:"39 €", mes:"/ Monat", items:["Alles aus Basis","Fotos deines Ladens","Du stehst in deiner Stadt an erster Stelle","Veröffentliche Neuigkeiten und Aktionen","Statistiken, wie viele dich sehen"] },
        { n:"Premium", b:"Maßgeschneidert", precio:"Auf Anfrage", mes:"", items:["Alles aus Hervorgehoben","Top-Platzierung in deiner Provinz","Kampagnen und Kooperationen mit Brosin"] }],
      nota: "Richtpreise, Änderungen während der Startphase vorbehalten.",
      cta: "Trag deinen Laden kostenlos ein",
      dudas: "Fragen? Schreib an <b>hola@brosin.app</b>, WhatsApp <b>+34 644 46 61 34</b> oder Instagram <b>@brosinculture</b>." }
  };

  P.fr = {
    nos: { t: "À propos",
      lead: "Brosin est né en <b>2018 à Torre del Mar (Málaga)</b>, fondé par deux amis avec un rêve commun : créer un club social de fumeurs différent, où la <b>qualité</b> et la <b>communauté</b> passent avant tout.",
      quote: "« B » de be, d'être. Rosin, la résine. Bee, l'abeille.",
      firma: "Bro, no te quedes sin, Brosin.",
      p1: "De ce premier local est née une ruche : aujourd'hui nous sommes plusieurs espaces — <b>« DogRoom by Brosin »</b>, <b>« El Submarino by Brosin »</b> et d'autres — sur la Costa del Sol et la Costa Tropical, toujours avec le même œil, le même sourire et la même bonne humeur.",
      h_app: "Ce qu'est cette app",
      p_app: "Brosin est la carte de référence pour trouver <b>clubs sociaux, grow shops et boutiques de CBD</b> dans toute l'Espagne et l'Europe, avec des informations fiables et de la réduction des risques. Nous ne vendons pas de cannabis : nous sommes un guide d'information et de communauté.",
      h_mis: "Mission",
      p_mis: "Que la communauté cannabique se retrouve sans préjugés, avec une vraie qualité, une ambiance détendue et la proximité d'un pote — quels que soient ton âge, ton mode de vie ou tes connaissances sur le cannabis.",
      h_vis: "Vision",
      p_vis: "Être la marque de clubs sociaux de cannabis la plus reconnaissable d'Espagne, et la référence en Europe, sans jamais perdre l'âme de quartier avec laquelle tout a commencé à Torre del Mar.",
      h_val: "Ce qui ne se négocie pas",
      vals: [["La qualité, sans raccourcis","Le produit, le local et jusqu'au verre, soignés dans le détail."],
             ["Naturel, comme le miel","On parle clair, sans artifices ni frime."],
             ["Audacieux avec discernement","Au-delà de l'attendu, sans devenir du bruit."],
             ["La ruche d'abord","Le membre de 20 ans et celui de 85 partagent la table et se sentent chez eux."]],
      pie: "Brosin promeut une consommation responsable et la réduction des risques. Réservé aux +18." },
    emp: { t: "Pour les professionnels", sub: "Entre sur la carte de référence",
      lead: "Tu as un <b>club social, grow shop ou une boutique de CBD</b> ? Apparais sur Brosin et touche les gens qui cherchent justement ce que tu proposes. <b>Commencer est gratuit.</b>",
      h_por: "Pourquoi être sur Brosin",
      por: ["<b>Visibilité gratuite</b> auprès d'une communauté qui cherche clubs, grow shops et CBD.",
            "Tu apparais sur la <b>carte de ta zone</b> ainsi que dans les recherches et filtres par province.",
            "Tu pourras <b>publier tes actus et promotions</b> (très bientôt).",
            "Tu fais partie d'une <b>marque avec une identité</b> et d'une communauté réelle."],
      h_tar: "Tarifs",
      planes: [
        { n:"Basique", b:"Gratuit", precio:"0 €", mes:"", items:["Fiche vérifiée sur la carte","Coordonnées et horaires","Tu apparais dans les recherches et filtres"] },
        { n:"Mis en avant", b:"Le plus choisi", precio:"39 €", mes:"/ mois", items:["Tout le plan Basique","Photos de ton local","Tu apparais en premier dans ta ville","Publie tes actus et promotions","Statistiques de visibilité"] },
        { n:"Premium", b:"Sur mesure", precio:"Sur devis", mes:"", items:["Tout le plan Mis en avant","Position privilégiée dans ta province","Campagnes et collaborations avec Brosin"] }],
      nota: "Tarifs indicatifs, susceptibles d'évoluer pendant la phase de lancement.",
      cta: "Ajoute ton local gratuitement",
      dudas: "Des questions ? Écris à <b>hola@brosin.app</b>, WhatsApp <b>+34 644 46 61 34</b> ou Instagram <b>@brosinculture</b>." }
  };

  P.nl = {
    nos: { t: "Over ons",
      lead: "Brosin ontstond in <b>2018 in Torre del Mar (Málaga)</b>, opgericht door twee vrienden met dezelfde droom: een andere social club voor rokers bouwen, waar <b>kwaliteit</b> en <b>gemeenschap</b> voorop staan.",
      quote: "\"B\" van be, van zijn. Rosin, de hars. Bee, de bij.",
      firma: "Bro, no te quedes sin, Brosin.",
      p1: "Uit die eerste zaak groeide een korf: vandaag zijn we meerdere plekken — <b>«DogRoom by Brosin»</b>, <b>«El Submarino by Brosin»</b> en meer — langs de Costa del Sol en de Costa Tropical, altijd met hetzelfde oog, dezelfde glimlach en dezelfde goede sfeer.",
      h_app: "Wat deze app is",
      p_app: "Brosin is de referentiekaart om <b>social clubs, growshops en CBD-winkels</b> in heel Spanje en Europa te vinden, met eerlijke informatie en schadebeperking. We verkopen geen cannabis: we zijn een informatie- en communitygids.",
      h_mis: "Missie",
      p_mis: "Dat de cannabisgemeenschap samenkomt zonder vooroordelen, met echte kwaliteit, een ontspannen sfeer en de warmte van een maat — ongeacht je leeftijd, je leefstijl of hoeveel je van cannabis weet.",
      h_vis: "Visie",
      p_vis: "Het meest herkenbare merk van cannabis social clubs in Spanje zijn, en de maatstaf in Europa, zonder ooit de buurtziel te verliezen waarmee het in Torre del Mar begon.",
      h_val: "Waarover we niet onderhandelen",
      vals: [["Kwaliteit zonder omwegen","Het product, de zaak en zelfs het glas, tot in detail verzorgd."],
             ["Natuurlijk, als honing","We praten helder, zonder opsmuk of poeha."],
             ["Gedurfd, maar met verstand","Verder dan verwacht, zonder ruis te worden."],
             ["De korf eerst","Het lid van 20 en dat van 85 delen een tafel en voelen zich thuis."]],
      pie: "Brosin staat voor verantwoord gebruik en schadebeperking. Alleen 18+." },
    emp: { t: "Voor ondernemers", sub: "Kom op de referentiekaart",
      lead: "Heb je een <b>social club, growshop of CBD-winkel</b>? Kom op Brosin te staan en bereik precies de mensen die zoeken wat jij aanbiedt. <b>Beginnen is gratis.</b>",
      h_por: "Waarom op Brosin",
      por: ["<b>Gratis zichtbaarheid</b> bij een community die zoekt naar clubs, growshops en CBD.",
            "Je staat op de <b>kaart van jouw omgeving</b> en in de zoekresultaten en provinciefilters.",
            "Je kunt straks <b>je nieuwtjes en acties plaatsen</b> (binnenkort).",
            "Je maakt deel uit van een <b>merk met identiteit</b> en een echte community."],
      h_tar: "Tarieven",
      planes: [
        { n:"Basis", b:"Gratis", precio:"€ 0", mes:"", items:["Geverifieerde vermelding op de kaart","Contactgegevens en openingstijden","Je verschijnt in zoekopdrachten en filters"] },
        { n:"Uitgelicht", b:"Meest gekozen", precio:"€ 39", mes:"/ maand", items:["Alles uit Basis","Foto's van je zaak","Je staat bovenaan in jouw stad","Plaats je nieuwtjes en acties","Statistieken over je bereik"] },
        { n:"Premium", b:"Op maat", precio:"Op aanvraag", mes:"", items:["Alles uit Uitgelicht","Toppositie in jouw provincie","Campagnes en samenwerkingen met Brosin"] }],
      nota: "Richtprijzen, kunnen wijzigen tijdens de lanceringsfase.",
      cta: "Voeg je zaak gratis toe",
      dudas: "Vragen? Schrijf naar <b>hola@brosin.app</b>, WhatsApp <b>+34 644 46 61 34</b> of Instagram <b>@brosinculture</b>." }
  };

  P.it = {
    nos: { t: "Chi siamo",
      lead: "Brosin è nato nel <b>2018 a Torre del Mar (Málaga)</b>, fondato da due amici con un sogno comune: creare un club sociale di fumatori diverso, dove <b>qualità</b> e <b>comunità</b> venissero prima di tutto.",
      quote: "\"B\" di be, di essere. Rosin, la resina. Bee, l'ape.",
      firma: "Bro, no te quedes sin, Brosin.",
      p1: "Da quel primo locale è nato un alveare: oggi siamo diversi spazi — <b>«DogRoom by Brosin»</b>, <b>«El Submarino by Brosin»</b> e altri — lungo la Costa del Sol e la Costa Tropical, sempre con lo stesso occhio, lo stesso sorriso e la stessa bella energia.",
      h_app: "Cos'è questa app",
      p_app: "Brosin è la mappa di riferimento per trovare <b>club sociali, grow shop e negozi di CBD</b> in tutta la Spagna e in Europa, con informazioni oneste e riduzione del danno. Non vendiamo cannabis: siamo una guida informativa e di comunità.",
      h_mis: "Missione",
      p_mis: "Che la comunità cannabica si incontri senza pregiudizi, con qualità vera, atmosfera rilassata e la vicinanza di un amico — a prescindere dalla tua età, dal tuo stile di vita o da quanto sai di cannabis.",
      h_vis: "Visione",
      p_vis: "Essere il marchio di club sociali di cannabis più riconoscibile di Spagna, e il riferimento in Europa, senza perdere mai l'anima di quartiere con cui è nato a Torre del Mar.",
      h_val: "Su cosa non trattiamo",
      vals: [["Qualità senza scorciatoie","Il prodotto, il locale e perfino il bicchiere, curati nel dettaglio."],
             ["Naturale, come il miele","Parliamo chiaro, senza fronzoli né apparenza."],
             ["Audaci con criterio","Oltre l'atteso, senza diventare rumore."],
             ["Prima l'alveare","Il socio di 20 anni e quello di 85 condividono il tavolo e si sentono a casa."]],
      pie: "Brosin promuove il consumo responsabile e la riduzione del danno. Solo +18." },
    emp: { t: "Per le aziende", sub: "Entra nella mappa di riferimento",
      lead: "Hai un <b>club sociale, grow shop o negozio di CBD</b>? Fatti trovare su Brosin e raggiungi le persone che stanno cercando proprio quello che offri. <b>Iniziare è gratis.</b>",
      h_por: "Perché stare su Brosin",
      por: ["<b>Visibilità gratuita</b> presso una comunità che cerca club, grow shop e CBD.",
            "Compari sulla <b>mappa della tua zona</b> e nelle ricerche e nei filtri per provincia.",
            "Potrai <b>pubblicare novità e promozioni</b> (molto presto).",
            "Fai parte di un <b>marchio con identità</b> e di una comunità reale."],
      h_tar: "Tariffe",
      planes: [
        { n:"Base", b:"Gratis", precio:"0 €", mes:"", items:["Scheda verificata sulla mappa","Contatti e orari","Compari nelle ricerche e nei filtri"] },
        { n:"In evidenza", b:"Il più scelto", precio:"39 €", mes:"/ mese", items:["Tutto il piano Base","Foto del tuo locale","Compari per primo nella tua città","Pubblica novità e promozioni","Statistiche su quante persone ti vedono"] },
        { n:"Premium", b:"Su misura", precio:"Su richiesta", mes:"", items:["Tutto il piano In evidenza","Posizione di rilievo nella tua provincia","Campagne e collaborazioni con Brosin"] }],
      nota: "Tariffe indicative, soggette a modifiche durante la fase di lancio.",
      cta: "Aggiungi il tuo locale, gratis",
      dudas: "Dubbi? Scrivici a <b>hola@brosin.app</b>, WhatsApp <b>+34 644 46 61 34</b> o Instagram <b>@brosinculture</b>." }
  };

  P.pt = {
    nos: { t: "Sobre nós",
      lead: "A Brosin nasceu em <b>2018 em Torre del Mar (Málaga)</b>, fundada por dois amigos com um sonho comum: criar um clube social de fumadores diferente, onde a <b>qualidade</b> e a <b>comunidade</b> viessem em primeiro lugar.",
      quote: "\"B\" de be, de ser. Rosin, a resina. Bee, a abelha.",
      firma: "Bro, no te quedes sin, Brosin.",
      p1: "Daquele primeiro espaço nasceu uma colmeia: hoje somos vários locais — <b>«DogRoom by Brosin»</b>, <b>«El Submarino by Brosin»</b> e mais — pela Costa del Sol e pela Costa Tropical, sempre com o mesmo olhar, o mesmo sorriso e a mesma boa onda.",
      h_app: "O que é esta app",
      p_app: "A Brosin é o mapa de referência para encontrar <b>clubes sociais, grow shops e lojas de CBD</b> por toda a Espanha e Europa, com informação verdadeira e redução de riscos. Não vendemos canábis: somos um guia informativo e de comunidade.",
      h_mis: "Missão",
      p_mis: "Que a comunidade canábica se junte sem preconceitos, com qualidade a sério, ambiente descontraído e a proximidade de um amigo — independentemente da tua idade, do teu estilo de vida ou do que saibas sobre canábis.",
      h_vis: "Visão",
      p_vis: "Ser a marca de clubes sociais de canábis mais reconhecível de Espanha, e a referência na Europa, sem nunca perder a essência de bairro com que nasceu em Torre del Mar.",
      h_val: "O que não se negoceia",
      vals: [["Qualidade sem atalhos","O produto, o espaço e até o copo, cuidados ao detalhe."],
             ["Natural, como o mel","Falamos claro, sem artifícios nem fachada."],
             ["Atrevida com critério","Para além do esperado, sem virar ruído."],
             ["A colmeia primeiro","O sócio de 20 e o de 85 partilham a mesa e sentem-se em casa."]],
      pie: "A Brosin promove o consumo responsável e a redução de riscos. Só +18." },
    emp: { t: "Para empresários", sub: "Entra no mapa de referência",
      lead: "Tens um <b>clube social, grow shop ou loja de CBD</b>? Aparece na Brosin e chega às pessoas que procuram exatamente o que ofereces. <b>Começar é grátis.</b>",
      h_por: "Porquê estar na Brosin",
      por: ["<b>Visibilidade grátis</b> junto de uma comunidade que procura clubes, grow shops e CBD.",
            "Apareces no <b>mapa da tua zona</b> e nas pesquisas e filtros por distrito.",
            "Vais poder <b>publicar as tuas novidades e promoções</b> (muito em breve).",
            "Fazes parte de uma <b>marca com identidade</b> e de uma comunidade real."],
      h_tar: "Preços",
      planes: [
        { n:"Básico", b:"Grátis", precio:"0 €", mes:"", items:["Ficha verificada no mapa","Contactos e horário","Apareces nas pesquisas e filtros"] },
        { n:"Destacado", b:"O mais escolhido", precio:"39 €", mes:"/ mês", items:["Tudo o do plano Básico","Fotos do teu espaço","Apareces em primeiro na tua cidade","Publica as tuas novidades e promoções","Estatísticas de quantas pessoas te veem"] },
        { n:"Premium", b:"À medida", precio:"Sob consulta", mes:"", items:["Tudo o do plano Destacado","Posição destacada no teu distrito","Campanhas e colaborações com a Brosin"] }],
      nota: "Preços indicativos, sujeitos a alterações durante a fase de lançamento.",
      cta: "Adiciona o teu local, grátis",
      dudas: "Dúvidas? Escreve para <b>hola@brosin.app</b>, WhatsApp <b>+34 644 46 61 34</b> ou Instagram <b>@brosinculture</b>." }
  };

  P.pl = {
    nos: { t: "O nas",
      lead: "Brosin powstał w <b>2018 roku w Torre del Mar (Málaga)</b>, założony przez dwóch przyjaciół z jednym marzeniem: stworzyć inny klub społeczny dla palaczy, w którym <b>jakość</b> i <b>wspólnota</b> są na pierwszym miejscu.",
      quote: "„B\" jak be, jak być. Rosin, żywica. Bee, pszczoła.",
      firma: "Bro, no te quedes sin, Brosin.",
      p1: "Z tego pierwszego lokalu wyrósł ul: dziś jesteśmy kilkoma miejscami — <b>«DogRoom by Brosin»</b>, <b>«El Submarino by Brosin»</b> i innymi — na Costa del Sol i Costa Tropical, zawsze z tym samym okiem, tym samym uśmiechem i tą samą dobrą energią.",
      h_app: "Czym jest ta aplikacja",
      p_app: "Brosin to mapa odniesienia, na której znajdziesz <b>kluby społeczne, grow shopy i sklepy CBD</b> w całej Hiszpanii i Europie, z rzetelnymi informacjami i ograniczaniem ryzyka. Nie sprzedajemy konopi: jesteśmy przewodnikiem informacyjnym i społecznością.",
      h_mis: "Misja",
      p_mis: "Aby społeczność konopna spotykała się bez uprzedzeń, z prawdziwą jakością, w luźnej atmosferze i z bliskością kumpla — niezależnie od wieku, stylu życia czy tego, ile wiesz o konopiach.",
      h_vis: "Wizja",
      p_vis: "Być najbardziej rozpoznawalną marką konopnych klubów społecznych w Hiszpanii i punktem odniesienia w Europie, nie tracąc nigdy sąsiedzkiego ducha, z którym zaczęło się w Torre del Mar.",
      h_val: "O czym nie dyskutujemy",
      vals: [["Jakość bez skrótów","Produkt, lokal, a nawet szklanka — dopracowane w szczegółach."],
             ["Naturalnie, jak miód","Mówimy wprost, bez ozdobników i pozerstwa."],
             ["Odważnie, ale z głową","Poza to, czego się spodziewasz, nie stając się hałasem."],
             ["Ul przede wszystkim","Członek w wieku 20 i ten w wieku 85 lat siedzą przy jednym stole i czują się jak w domu."]],
      pie: "Brosin promuje odpowiedzialne używanie i ograniczanie ryzyka. Tylko 18+." },
    emp: { t: "Dla firm", sub: "Wejdź na mapę odniesienia",
      lead: "Masz <b>klub społeczny, grow shop albo sklep CBD</b>? Pojaw się na Brosin i dotrzyj do ludzi, którzy szukają dokładnie tego, co oferujesz. <b>Start jest darmowy.</b>",
      h_por: "Dlaczego warto być na Brosin",
      por: ["<b>Darmowa widoczność</b> wśród społeczności szukającej klubów, grow shopów i CBD.",
            "Pojawiasz się na <b>mapie swojej okolicy</b> oraz w wyszukiwaniu i filtrach po prowincjach.",
            "Będziesz mógł <b>publikować nowości i promocje</b> (wkrótce).",
            "Jesteś częścią <b>marki z charakterem</b> i prawdziwej społeczności."],
      h_tar: "Cennik",
      planes: [
        { n:"Podstawowy", b:"Za darmo", precio:"0 €", mes:"", items:["Zweryfikowana wizytówka na mapie","Dane kontaktowe i godziny","Pojawiasz się w wyszukiwaniu i filtrach"] },
        { n:"Wyróżniony", b:"Najczęściej wybierany", precio:"39 €", mes:"/ miesiąc", items:["Wszystko z planu Podstawowego","Zdjęcia twojego lokalu","Jesteś pierwszy w swoim mieście","Publikuj nowości i promocje","Statystyki, ile osób cię widzi"] },
        { n:"Premium", b:"Na miarę", precio:"Do uzgodnienia", mes:"", items:["Wszystko z planu Wyróżnionego","Eksponowana pozycja w twojej prowincji","Kampanie i współprace z Brosin"] }],
      nota: "Ceny orientacyjne, mogą się zmienić w fazie startowej.",
      cta: "Dodaj swoje miejsce za darmo",
      dudas: "Pytania? Napisz na <b>hola@brosin.app</b>, WhatsApp <b>+34 644 46 61 34</b> lub Instagram <b>@brosinculture</b>." }
  };

  P.ru = {
    nos: { t: "О нас",
      lead: "Brosin появился в <b>2018 году в Торре-дель-Мар (Малага)</b>. Его основали двое друзей с общей мечтой: создать другой социальный клуб для курильщиков — такой, где на первом месте <b>качество</b> и <b>сообщество</b>.",
      quote: "«B» — от be, «быть». Rosin — смола. Bee — пчела.",
      firma: "Bro, no te quedes sin, Brosin.",
      p1: "Из того первого места вырос улей: сегодня у нас несколько пространств — <b>«DogRoom by Brosin»</b>, <b>«El Submarino by Brosin»</b> и другие — по Коста-дель-Соль и Коста-Тропикаль, всегда с тем же взглядом, той же улыбкой и тем же настроением.",
      h_app: "Что это за приложение",
      p_app: "Brosin — это справочная карта, где можно найти <b>социальные клубы, гроушопы и магазины CBD</b> по всей Испании и Европе, с достоверной информацией и снижением вреда. Мы не продаём каннабис: мы информационный справочник и сообщество.",
      h_mis: "Миссия",
      p_mis: "Чтобы каннабис-сообщество собиралось без предрассудков — с настоящим качеством, спокойной атмосферой и теплом, как от приятеля, независимо от возраста, образа жизни и того, много ли ты знаешь о каннабисе.",
      h_vis: "Видение",
      p_vis: "Стать самым узнаваемым брендом каннабис-клубов в Испании и ориентиром в Европе, не потеряв при этом ту районную душу, с которой всё начиналось в Торре-дель-Мар.",
      h_val: "О чём мы не торгуемся",
      vals: [["Качество без срезания углов","Продукт, само место и даже стакан — всё с вниманием к деталям."],
             ["Естественно, как мёд","Говорим прямо, без прикрас и позёрства."],
             ["Смело, но с головой","Дальше ожидаемого, но не превращаясь в шум."],
             ["Улей прежде всего","Член клуба в 20 и в 85 сидят за одним столом и чувствуют себя как дома."]],
      pie: "Brosin выступает за ответственное употребление и снижение вреда. Только 18+." },
    emp: { t: "Для бизнеса", sub: "Попади на справочную карту",
      lead: "У тебя <b>социальный клуб, гроушоп или магазин CBD</b>? Появись на Brosin и дотянись до людей, которые как раз ищут то, что ты предлагаешь. <b>Начать бесплатно.</b>",
      h_por: "Зачем быть на Brosin",
      por: ["<b>Бесплатная видимость</b> для сообщества, которое ищет клубы, гроушопы и CBD.",
            "Ты появляешься на <b>карте своего района</b>, а также в поиске и фильтрах по провинциям.",
            "Скоро сможешь <b>публиковать свои новости и акции</b> (в разработке).",
            "Ты часть <b>бренда с характером</b> и настоящего сообщества."],
      h_tar: "Тарифы",
      planes: [
        { n:"Базовый", b:"Бесплатно", precio:"0 €", mes:"", items:["Проверенная карточка на карте","Контакты и часы работы","Появляешься в поиске и фильтрах"] },
        { n:"Выделенный", b:"Выбирают чаще всего", precio:"39 €", mes:"/ месяц", items:["Всё из Базового","Фотографии заведения","Ты первый в своём городе","Публикуй новости и акции","Статистика, сколько человек тебя видит"] },
        { n:"Премиум", b:"Индивидуально", precio:"По запросу", mes:"", items:["Всё из Выделенного","Приоритетное место в твоей провинции","Кампании и сотрудничество с Brosin"] }],
      nota: "Цены ориентировочные, могут измениться на этапе запуска.",
      cta: "Добавь своё заведение бесплатно",
      dudas: "Вопросы? Пиши на <b>hola@brosin.app</b>, WhatsApp <b>+34 644 46 61 34</b> или Instagram <b>@brosinculture</b>." }
  };

  function get(lang) { return P[lang] || P.en || P.es; }

  root.BrosinPaginas = { data: P, get: get, langs: function () { return Object.keys(P); } };

})(typeof window !== 'undefined' ? window : globalThis);

if (typeof module !== 'undefined' && module.exports) module.exports = globalThis.BrosinPaginas;
