/* ===========================================================
   BROSIN · locales publicados
   Generado por _dev/build-publico.js — NO editar a mano.
   Para añadir o quitar, edita _dev/consentimientos.js y vuelve
   a ejecutar el script.

   20 locales, todos con consentimiento registrado.
   La base completa (2135 fichas) NO se publica: vive solo
   en la carpeta del proyecto.
   =========================================================== */
window.CLUBS = [
  {id:1, name:"Brosin", type:"csc", brosin:true, ccaa:"Andalucía", prov:"Málaga", city:"Torre del Mar", address:"Av. Doctor Marañón, 16, 29740 Torre del Mar, Málaga", lat:36.7405, lng:-4.095, phone:"", hours:"Todos los días 12:00–23:30", verified:true, rating:0, reviews:0, tags:["Casa madre"], desc:"Donde nació Brosin en 2018. El origen y el corazón de la colmena", email:"", web:"brosin.es", consent:"2026-07-30", consentVia:"propio"},
  {id:2, name:"DogRoom", type:"csc", brosin:true, ccaa:"Andalucía", prov:"Málaga", city:"Benalmádena", address:"Av. Federico García Lorca, 28, bloque F, 29631 Benalmádena, Málaga", lat:36.5987, lng:-4.5165, phone:"", hours:"Todos los días 12:00–00:00 · solo +21", verified:true, rating:3.5, reviews:19, tags:["+21"], desc:"Un espacio especial entre Arroyo de la Miel y Benalmádena", email:"", ig:"dogroomcsc", consent:"2026-07-30", consentVia:"propio"},
  {id:3, name:"Lighthouse", type:"csc", brosin:true, ccaa:"Andalucía", prov:"Málaga", city:"Torrox Costa", address:"Paseo marítimo, Torrox Costa, Málaga (dirección por confirmar)", lat:36.729, lng:-3.953, phone:"", hours:"", verified:true, rating:0, reviews:0, tags:["Frente al mar"], desc:"En pleno paseo marítimo, junto a un faro antiguo.", email:"", consent:"2026-07-30", consentVia:"propio"},
  {id:4, name:"El Submarino", type:"csc", brosin:true, ccaa:"Andalucía", prov:"Málaga", city:"Nerja", address:"C. Hibiscos, 29780 Nerja, Málaga", lat:36.744, lng:-3.877, phone:"", hours:"Todos los días 12:00–00:00 · solo +21", verified:true, rating:0, reviews:0, tags:["+21","Único"], desc:"Bajo la piscina: ventanas reales con miles de litros de agua sobre tu cabeza", email:"", ig:"elsubmarino.nerja", consent:"2026-07-30", consentVia:"propio"},
  {id:5, name:"Tropical Sexy", type:"csc", brosin:true, ccaa:"Andalucía", prov:"Granada", city:"Almuñécar", address:"Casco antiguo, Almuñécar, Granada (dirección por confirmar)", lat:36.734, lng:-3.692, phone:"", hours:"", verified:true, rating:0, reviews:0, tags:["Costa Tropical"], desc:"En pleno casco antiguo, a un minuto de la playa.", email:"", consent:"2026-07-30", consentVia:"propio"},
  {id:6, name:"La Casa 420", type:"csc", brosin:true, ccaa:"Andalucía", prov:"Málaga", city:"Algarrobo Costa", address:"Algarrobo-Costa, Málaga (primera línea de playa)", lat:36.748, lng:-4.042, phone:"", hours:"", verified:true, rating:5, reviews:10, tags:["Vistas al mar"], desc:"Local magnífico con vistas al mar. «Mi casa es tu casa». Valorado 5,0★ en Weedmaps.", email:"", consent:"2026-07-30", consentVia:"propio"},
  {id:26, name:"Cibidy CBD", type:"cbd", brosin:false, ccaa:"Andalucía", prov:"Sevilla", city:"Sevilla", address:"Calle Valle 2, local 3, 41003 Sevilla", lat:37.393966, lng:-5.984346, phone:"624 829 727", hours:"10:00-14:00 y 17:00-21:00", verified:true, rating:0, reviews:0, tags:["Alta verificada","CBD"], desc:"", email:"thecibidy@gmail.com", ig:"cibidyy", consent:"2026-08-03", consentVia:"formulario"},
  {id:150, name:"CBweed Ferrol", type:"cbd", brosin:false, ccaa:"Galicia", prov:"A Coruña", city:"Ferrol", address:"Rúa Real 148, bajo, 15402 Ferrol, A Coruña", lat:43.482462, lng:-8.236698, phone:"657 864 233", hours:"", verified:true, rating:0, reviews:0, tags:["Alta verificada","CBD"], desc:"", email:"cbweedferrol@hotmail.com", ig:"cbweedspain", consent:"2026-07-17", consentVia:"formulario"},
  {id:170, name:"Grow Shop Benidorm (Supernatural)", type:"grow", brosin:false, ccaa:"Comunidad Valenciana", prov:"Alicante", city:"Benidorm", address:"Calle Maravall 8, local Supernatural, 03501 Benidorm, Alicante", lat:38.53919, lng:-0.13498, phone:"", hours:"", verified:true, rating:0, reviews:0, tags:["Alta verificada","Cultivo"], desc:"", email:"roberto-x@tiscali.it", ig:"growshop_benidorm_supernatural", consent:"2026-07-17", consentVia:"formulario"},
  {id:212, name:"Allora Labs", type:"empresa", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Viladecans", address:"Camí de les Filipines 110, 08840 Viladecans, Barcelona", lat:41.305, lng:2.045, phone:"675 22 66 19", hours:"", verified:true, rating:0, reviews:0, tags:["Alta verificada","Laboratorio","Análisis"], desc:"", email:"info@alloralabs.es", web:"alloralabs.es", ig:"alloralabs", consent:"2026-07-17", consentVia:"formulario"},
  {id:715, name:"Zibidi Flowers", type:"cbd", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Alcobendas", address:"Calle Ruperto Chapí 57, 28100 Alcobendas, Madrid", lat:40.548085, lng:-3.643906, phone:"604 855 875", hours:"", verified:true, rating:0, reviews:0, tags:["Alta verificada","CBD"], desc:"", email:"rupertocbd@gmail.com", web:"zibidi.es", ig:"zibidiflow", consent:"2026-07-17", consentVia:"formulario"},
  {id:797, name:"Santa Grow Shop", type:"grow", brosin:false, ccaa:"Canarias", prov:"Santa Cruz de Tenerife", city:"Santa Cruz de Tenerife", address:"Calle General Serrano 65, local comercial, 38006 Santa Cruz de Tenerife", lat:28.466762, lng:-16.259897, phone:"922 092 804", hours:"L-V 10:00-13:30 y 16:30-20:00 · S 10:00-14:00", verified:true, rating:0, reviews:0, tags:["Alta verificada","Grow"], desc:"", email:"info@santagrow.es", web:"santagrow.es", ig:"santagrow.es", consent:"2026-08-04", consentVia:"formulario"},
  {id:957, name:"PowerCogollo Grow Shop", type:"grow", brosin:false, ccaa:"Comunidad Valenciana", prov:"Castellón", city:"Castellón de la Plana", address:"Calle Alcalá de Xivert 2, nave, 12004 Castellón de la Plana", lat:39.972179, lng:-0.052312, phone:"964 217 647", hours:"L-V 10:00-14:00 y 17:00-20:30 · S 10:30-14:00", verified:true, rating:0, reviews:0, tags:["Alta verificada","Grow"], desc:"", email:"info@powercogollo.com", web:"powercogollo.com", consent:"2026-08-04", consentVia:"formulario"},
  {id:1061, name:"Islaverde Grow Shop", type:"grow", brosin:false, ccaa:"Canarias", prov:"Las Palmas", city:"Playa Honda", address:"Calle San Borondón 52, 35509 Playa Honda, Lanzarote", lat:28.95344, lng:-13.5913, phone:"616 996 827", hours:"9:30-14:15 y 18:00-20:00", verified:true, rating:0, reviews:0, tags:["Alta verificada","Grow"], desc:"", email:"islaverdelanzarote@gmail.com", web:"islaverdegrowshop.com", consent:"2026-08-05", consentVia:"formulario"},
  {id:1587, name:"Luxury Growseeds", type:"grow", brosin:false, ccaa:"Comunidad Valenciana", prov:"Valencia", city:"Alzira", address:"Calle Cristóbal Monterde 31, bajo C, 46600 Alzira, Valencia", lat:39.15122, lng:-0.437, phone:"640 771 442", hours:"", verified:true, rating:0, reviews:0, tags:["Alta verificada","Grow","Semillas"], desc:"", email:"luxurygrowseeds@gmail.com", web:"luxurygrowseeds.com", ig:"luxury.growseeds", consent:"2026-08-03", consentVia:"formulario"},
  {id:1637, name:"Native Growshop", type:"grow", brosin:false, ccaa:"Castilla y León", prov:"Burgos", city:"Burgos", address:"Calle Regino Sáinz de la Maza 13, 09004 Burgos", lat:42.343122, lng:-3.692114, phone:"678 667 470", hours:"", verified:true, rating:0, reviews:0, tags:["Alta verificada","Grow"], desc:"", email:"nativegrowshop@gmail.com", ig:"nativegrowshopburgos", consent:"2026-07-17", consentVia:"formulario"},
  {id:2213, name:"420 Grow Shop Ferrol", type:"grow", brosin:false, ccaa:"Galicia", prov:"A Coruña", city:"Ferrol", address:"Rúa Coruña 10-12, bajo, 15401 Ferrol, A Coruña", lat:43.482025, lng:-8.23435, phone:"614 548 821", hours:"", verified:true, rating:0, reviews:0, tags:["Alta verificada"], desc:"", email:"420growshopferrol26@gmail.com", ig:"420growshop_ferrol", consent:"2026-07-17", consentVia:"formulario"},
  {id:2214, name:"The Nature CBD (Barrio de Salamanca)", type:"cbd", brosin:false, ccaa:"Madrid", prov:"Madrid", city:"Madrid", address:"Calle General Díaz Porlier 38, 28001 Madrid", lat:40.428411, lng:-3.6768, phone:"919 355 589", hours:"", verified:true, rating:0, reviews:0, tags:["Alta verificada"], desc:"", email:"info@thenaturecbd.com", web:"thenaturecbd.com", consent:"2026-07-17", consentVia:"formulario"},
  {id:2215, name:"Cannabity Sabadell", type:"cbd", brosin:false, ccaa:"Cataluña", prov:"Barcelona", city:"Sabadell", address:"Carrer Gràcia 48b, 08201 Sabadell, Barcelona", lat:41.548477, lng:2.106516, phone:"640 879 627", hours:"L-S 10:00-13:30 y 17:00-20:30", verified:true, rating:0, reviews:0, tags:["Alta verificada"], desc:"", email:"sabadell@cannabity.com", ig:"cannabitysabadell", consent:"2026-08-04", consentVia:"formulario"},
  {id:2216, name:"Green Dealer CBD", type:"cbd", brosin:false, ccaa:"Región de Murcia", prov:"Murcia", city:"Murcia", address:"Calle San Lorenzo 10B, local A, 30001 Murcia", lat:37.975874, lng:-1.070883, phone:"659 560 855", hours:"L-V 10:30-14:00 y 17:30-21:00", verified:true, rating:0, reviews:0, tags:["Alta verificada"], desc:"", email:"greendealercbd@gmail.com", ig:"greendealer.oficial", consent:"2026-08-05", consentVia:"formulario"}
];
window.CLUBS_EN_TRAMITE = 2115;
